### ISSUE TITLE
Natura berries cannot be harvested by ComputerCraft Turtles

### ISSUE THREAD

**Issue by jvanegmond** [progwml6/Natura#110]
As a player, I want to be able to harvest my Natura berries using ComputerCraft turtles. This is currently not possible.

Steps for reproduction:
- Place any Natura berry bush (for example, the blueberry bush)
- Let the blueberry bush fully grow
- Place a  ComputerCraft farming turtle facing the blueberry bush
- Right click the farming turtle to open its console.
- Enter the command lua (ENTER)
- Enter: turtle.dig()    (ENTER)

The result is that the farming turtle will dig out the bush, destroying the berry in the process. The expected result is that the blueberry bush will be harvested by the farming turtle so that the turtle will have a single berry in its inventory and leaving the bush intact. Which looks like this: http://i.imgur.com/zecbYR3.png

The command turtle.dig() or alternatively turtle.digDown() and turtle.digUp() when used on native Minecraft crops in combination with the farming turtle do work as expected. These can harvest wheat, carrots and possibly other crops.

I'm not sure whether this bug should be reported to Natura or ComputerCraft (or both) as I am unclear on the specifics of how ComputerCraft works in regards to farming and harvesting. Please advice.

Tested in versions:

Minecraft version 1.6.4
Natura version 2.1.14 (Natura_mc1.6.X_2.1.14.jar)
ComputerCraft 1.58
Forge version 9.11.1.965 (forge-1.6.4-9.11.1.965-installer.jar)

**Comment by matejdro** [comment]
This still occurs in 1.7.10 (can't reopen though since I'm not author of the mod).

**Comment by progwml6** [comment]
@matejdro please make a new ticket w/ logs for 1.7.10
