### ISSUE TITLE
Ghostwood trees not spawning in nether

### ISSUE THREAD

**Issue by RenolY2** [progwml6/Natura#192]
I am playing on a server that has version 2.2.0-b1 of Natura installed for Minecraft 1.7.10, forge v10.13.0.1207 is installed.

Even though, according to the server administrator, the generation of Ghostwood trees is enabled in the config file and the rarity of the tree is set to 10, I am unable to find any Ghostwood trees in the Nether even after searching for a long time, though I did find plenty of Bloodwood, Darkwood and Fusewood trees.

Looking at the source code for Ghostwood trees (the file that generates Ghostwood trees appears to be called WhiteTreeGen), it appears that the lattest commit for WhiteTreeGen.java changed the findGround function into one that wouldn't work in the Nether because the Nether has no dirt or grass. Maybe that causes the tree to not be spawned correctly or at all?

Compare http://github.com/progwml6/Natura/blob/9b1a1c5f0e9747cb263e9ccae2b91f45019bf497/src/main/java/mods/natura/worldgen/WhiteTreeGen.java#L462 (current version of file)
with http://github.com/progwml6/Natura/blob/d36ba2b7de6d5322173fc7206dd77d81926b8ec2/src/main/java/mods/natura/worldgen/WhiteTreeGen.java#L494 (previous version of file)

It also appears as if the newer commit overwrote some of the previously existing variables and comments with generic deobfuscated names, making the file harder to read, though that is unrelated to the functionality of the Ghostwood tree.

**Comment by BrizzleMFD** [comment]
This issue i believe to be caused by the fact that in the old code ghostwood trees would spawn on tainted soil (the purple stuff.) The current natura has removed the heatsand and the tainted soil from spawning in the nether. Presto no ghost wood. Seems pretty straightforward for the devs to fix

**Comment by progwml6** [comment]
there are a bunch of issues with the world generators... they are being completely rewritten for 1.8

**Comment by Sinhika** [comment]
See pull request #220

**Comment by Zsashas** [comment]
Are they being fixed for 1.7.10 as well, though? Seems like almost everyone would appreciate that.

**Comment by Sinhika** [comment]
My fix is for 1.7.10--there's a completely unofficial, personal release for it on my Natura fork at https://github.com/Sinhika/Natura/releases/tag/e14a8c3

**Comment by alexbegt** [comment]
I'll pull the fix right now.
