### ISSUE TITLE
Nether Lava Doesn't Flow

### ISSUE THREAD

**Issue by Mandabar** [progwml6/Natura#202]
All lava in the nether doesn't flow when Natura is installed. To narrow down the issue, Took out all mods
Installed
Forge 1231
Mantle .3.2 Jenkins build #184
Natura.1.7.10-81.36d486c

http://puu.sh/cjeq9/7307b44e86.png Mod List
http://puu.sh/cCKOf/dabb9feb63.jpg Lava in roof, not flowing.

Same issue in forge 1208

Update:
Removed Natura. Lave still doesn't flow in Natura genned world.

New world with no mods (Still forge though) and lava flows in Nether.

http://puu.sh/cjf87/b489ad4675.png Mod List
http://puu.sh/cjf4O/3852e284e3.jpg Lava Flowing

Edit: Fixed a incorrect word from natura to Nether at the end there. Oops. 
Added all photos to an imgur album in case The puush pictures expires before someone looks at the report. http://imgur.com/a/8p6hl

**Comment by smbarbour** [comment]
It would seem that this line is quite possibly the reason for this:  https://github.com/progwml6/Natura/blob/master/src/main/java/mods/natura/dimension/NetheriteChunkProvider.java#L520

The vanilla nether provider uses Blocks.flowing_lava, not Blocks.lava

**Comment by Zsashas** [comment]
So, is this getting fixed, or...?

**Comment by progwml6** [comment]
I am not updating 1.7.10 mods anymore as i'm focused on 1.9.4 mods ... I will gladly accept pull requests for the 1.7 mods

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
