### ISSUE TITLE
Crash when exploring the world

### ISSUE THREAD

**Issue by ChatFawkes** [progwml6/Natura#212]
[Crash Report](https://gist.github.com/ChatFawkes/3c22979c141d1070b4a1)
Natura Version: Build 97 (from your jenkins)

This happened when I was exploring a flatworld and seems to be related to cloud generation. When I load the world up again and try to go in the same direction, it crashes my game again with [this instead](https://gist.github.com/ChatFawkes/1db375413a1841925018).

**Comment by Adaptivity** [comment]
Fixed in Forge. Close it.
