### ISSUE TITLE
Redwoods grow from single saplings.

### ISSUE THREAD

**Issue by MoxieGrrl** [progwml6/Natura#215]
Tried with bonemeal and a single redwood sapling. Still waiting on the results from natural growth. And waiting...and waiting...

**Comment by squeek502** [comment]
Would have been fixed by #185

**Comment by Adaptivity** [comment]
@progwml6 maybe it still worth merging above mentioned PR? Most modders are gonna stay on 1.7.10 and skip 1.8. And it might worth to have clean Natura build for 1.7.10 too.

**Comment by progwml6** [comment]
i'm going to take another look at this at some point this week there should be a way to fix redwoods without breaking worlds.

**Comment by aionys** [comment]
I don't know if it's a mod conflict with something in Direwolf20's 1.10.2 modepack, but I've already looked into the config with no luck.

Redwood trees do NOT grow. At all. I've tried bone meal with no results, and I've had a 7x7 just sitting there for a real world week with the server running the whole time, and no redwoods at all.

**Comment by alexbegt** [comment]
Since this is from 2015, and redwood trees are not the same in 1.16, I am going to be closing this issue.
