### ISSUE TITLE
Minecraft error. Cant understand why its crash..

### ISSUE THREAD

**Issue by il-kuliko** [progwml6/Natura#216]
I use ftb infinity client. I decided to delete all mods and put only mods that i want.
![qwe](https://cloud.githubusercontent.com/assets/11243881/6426010/a5ca9002-bf5c-11e4-9635-aec9772d2cb5.jpg)
That list of mods thats work fine. As soon as I add WR-CBE, Its crash.
There was an error error associated with the fastcraft. I delete fastcraft and there it is. Crash once again. I totally dont understand anything.(sorry for my english)

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 28.02.15 15:06
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Unknown Source)
	at java.nio.DirectIntBufferU.put(Unknown Source)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:337)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:190)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:174)
	at codechicken.lib.render.TextureSpecial.func_94219_l(TextureSpecial.java:68)
	at net.minecraft.client.renderer.texture.TextureMap.func_94248_c(TextureMap.java:498)
	at net.minecraft.client.renderer.texture.TextureMap.func_110550_d(TextureMap.java:582)
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:154)
	at TextureUtils.resourcesReloaded(TextureUtils.java:277)
	at TextureUtils$1.func_110549_a(TextureUtils.java:305)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99)
	at TextureUtils.registerResourceListener(TextureUtils.java:309)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1188)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 920415880 bytes (877 MB) / 1783103488 bytes (1700 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -Xms256M -Xmx4096M -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 40 mods loaded, 40 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	betterstorage{0.12.0.124} [BetterStorage] (BetterStorage-1.7.10-0.12.0.124.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.667-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.667-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V4c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GeoStrata{Gamma} [GeoStrata] (GeoStrata 1.7.10 V4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mariculture{1.7.10-1.2.4d} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	neiintegration{1.0.6} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	neresources{0.1.0.86} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WailaHarvestability{1.1.1} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	wawla{1.0.9} [What Are We Looking At] (Wawla-1.0.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by fuj1n** [comment]
So why do you go to Natura when you don't even have it installed?

**Comment by il-kuliko** [comment]
Sorry dude:) What do you mean?

**Comment by il-kuliko** [comment]
I find somewhere in internet that i should delete options.txt and somehow it works for me...
Thanx god!!!!!

Now, i've copy mod foder to my notebook win8... Stupid laptop!!!!!
All mods are the same!!!! Why? Why it say to me "Forge mod loader has found a problem with your minecraft installation The mods and version listed below could not be found  -Tconstruct-"

Im look at it.  i see -Tconstruct- in my mod folder. Why in PC all the mods work, in laptop something goes wrong. It says that he save a log. I cant find it. I search it and no results found. I though that instalation folder is wrong. I look in settings , The folder is right.  I've delete folder. It download mods once again, i delete mods, put my mods. It totally dont want to notice Tconstruct. And i cant find log file((( 

Any ideas?
(Think i totaly have bad english, like a kid =D Im from Russia)

**Comment by TherminatorX** [comment]
@il-kuliko You posted an error about the mod "Natura," but that mod is not installed. This is not where you should go to report this error.

**Comment by il-kuliko** [comment]
I understand))))))) I just registered yesterday and dont know where should i have to post my errors))) sorry for post in wrong place)
