### ISSUE TITLE
[1.7.10] Can't disable Glowshroom in worldgen

### ISSUE THREAD

**Issue by Fickilty** [progwml6/Natura#217]
As the title reads, Glowshrooms are oddly absent in the config and I would greatly appreciate the ability to disable them.

No other mods present.

**Comment by Adaptivity** [comment]
@progwml6 going to take a look at this

**Comment by progwml6** [comment]
thanks @Adaptivity if you are on irc #progsmods is a great place to discuss pr plans

**Comment by Adaptivity** [comment]
I know. I will go to IRC if I have any questions :)
