### ISSUE TITLE
[1.7.10] Nether generation bugged

### ISSUE THREAD

**Issue by Fickilty** [progwml6/Natura#218]
Several things are happening:
Glowshrooms are spawning in each other, in lava, in netherrack/tainted soul
Bloodwood trees aren't spawning with enough space below them
Clouds are spawning in and out of other things
Nether Quartz is spawning in tainted soul
Ghostwood trees aren't spawning at all, even at a spawn rarity of 1
![2015-03-12_14 51 36](https://cloud.githubusercontent.com/assets/6948515/6612047/f7b20af6-c8c8-11e4-944f-06c7c5f25c6c.png)
![2015-03-12_14 54 46](https://cloud.githubusercontent.com/assets/6948515/6612049/fdaaa8a0-c8c8-11e4-9165-09dd4a307a73.png)
![2015-03-12_14 52 21](https://cloud.githubusercontent.com/assets/6948515/6612052/ff1f9db2-c8c8-11e4-8a59-e4c3b785bb1f.png)
![2015-03-12_14 52 50](https://cloud.githubusercontent.com/assets/6948515/6612051/ff1bb8aa-c8c8-11e4-8540-23c9e10204d6.png)

**Comment by TherminatorX** [comment]
As per the Ghostwood issue, see #192

**Comment by Sinhika** [comment]
Pull request #220 fixes the ghostwoods not generating (this bug and #192 ) in 1.7.10. I appreciate that you are busy working on the 1.8 update, but a lot of us play 1.7.10 and would like that code working, too.

**Comment by alexbegt** [comment]
I'll pull the fix right now.
