### ISSUE TITLE
[1.7.10] rotated Natura Woods interactions issues

### ISSUE THREAD

**Issue by skaviouz** [progwml6/Natura#219]
#### Premise: If you place ~~Logs~~ Wood sideways It'll read the wrong name.

This stops other mods interacting with the block (because it's a different block; i.e. botania, or waila).

#### Screen Shots:

The 1st screen shot is Sakura Wood.
The 2nd screen shot is Willow Wood.

![1](http://i.imgur.com/iAXAZca.png)
![2](http://i.imgur.com/9ZjMlG9.png)

#### Statistics:
natura-1.7.10-2.2.0.1
Botania r1.5-169
FML 7.10.85.1291 / Forge 10.13.2.1291

**Comment by Zsashas** [comment]
This is still an issue...

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
