### ISSUE TITLE
Forestry 3.5.0.8 crash

### ISSUE THREAD

**Issue by katur239** [progwml6/Natura#227]
Getting a crash loading up new forestry

http://pastebin.com/CnJ3bw3A

**Comment by dmodoomsirius** [comment]
Did you submit this to forestry as well?

**Comment by katur239** [comment]
Yes I did. Not sure whos end would need to fix it.

**Comment by dmodoomsirius** [comment]
```java
Forestry{3.5.0.8} [Forestry for Minecraft] (forestry_1.7.10-3.5.0.8.jar) Unloaded->Constructed->Pre-initialized->Errored
        BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Errored
```
found that so i would throw this at Forestry team and reference this issue.

**Comment by katur239** [comment]
I forgot about Binnie's mods, Right. Thanks.

Appears they already have a fix. Thanks.
https://github.com/ForestryMC/ForestryMC/issues/593
