### ISSUE TITLE
[1.7.10] Grown Glowshrooms don't appear until after a relog, nor drop blocks with Silk Touch

### ISSUE THREAD

**Issue by Fickilty** [progwml6/Natura#232]
The glowshroom blocks don't appear until either relogging or being right clicked. Block updates don't trigger their appearance either.

Silk touch on picks/axes/kamas doesn't make the glowshroom blocks either.
![2015-05-11_15 57 19](https://cloud.githubusercontent.com/assets/6948515/7559280/6a46cf68-f7f7-11e4-8aa0-5d0dec88da4f.png)

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
