### ISSUE TITLE
Some fusewood stuff not oredicted

### ISSUE THREAD

**Issue by Adaptivity** [progwml6/Natura#235]
Some Fusewood items/blocks are not registered in OreDict... I don't expect this getting fixed but still... maybe one day someone fork this and start working on it actually...
List of stuff:
1) Fusewood planks
2) Fusewood stairs
3) Some other stairs not oredicted too

**Comment by Parker8283** [comment]
What? We can have meta up to 15 for blocks...

**Comment by Adaptivity** [comment]
Heh, I don't really know much about modding but joshiejack said something like "That block doesn't exist. The metadata only goes up to 11. :P" on one of issues (It's called "More localization", you can check this) on Mariculture repository. This is why I thought it's related to metadata since fusewood stuff not oredicted for some reason.

**Comment by Zsashas** [comment]
He was referring to that particular block, which is only supposed to have metadata up to 11. In general, it goes higher.

**Comment by Adaptivity** [comment]
Ok, well. It still an issue since some fusewood stuff isn't oredicted.
