### ISSUE TITLE
Gostwood Overworld Wanabe

### ISSUE THREAD

**Issue by Kyrinon** [progwml6/Natura#237]
Even though the gostwood tree is a nether tree it has the growth conditions of an over world tree. this means that no mater how you change the cfg it will never naturally spawn. the sapling will pop off if it is updated while on tainted soil and will not grow while on nether rack it will only grow on dirt/grass. A quick patch would be much appreciated because this mod is very important in my mod pack. thanks

**Comment by progwml6** [comment]
new alpha is on curse that should fix this

**Comment by Kyrinon** [comment]
thanks

**Comment by Kyrinon** [comment]
Don't know if you will get this because the issue is closed but downloaded the beta did not work and on top of the other problems now the sapling is not rendering. will be looing forward to  the next update with the world gen rewrite. thanks for all the work you put into the mod

**Comment by progwml6** [comment]
screenshots please

**Comment by Adaptivity** [comment]
can't reproduce this at all.

**Comment by Kyrinon** [comment]
I was using version 2.2.0.1 when you mentioned there was a new alpha. Because i did not see any versions more recent than the one i was using i tried the 2.2.0.b1 that is the version in which the saplings where not rendering. here is a video of what i am talking about in the 2.2.0.1 version https://youtu.be/wvUIPPiP2y4
