### ISSUE TITLE
1.7 todos

### ISSUE THREAD

**Issue by Adaptivity** [progwml6/Natura#242]
There are still some todos in code to complete in 1.7, @progwml6 maybe you want to take a look.

**Comment by Adaptivity** [comment]
The most important problem here that wood blocks aren't burnable. I can easily fix it but then Nether Trees will burn too which is not supposed to happen I guess.
setBurnProperties was replaced with Blocks.fire.setFireInfo. I tried to set metadata for blocks and failed...

**Comment by progwml6** [comment]
1.10 is a complete rewrite
