### ISSUE TITLE
Allow Seed bags to be completely disabled in config

### ISSUE THREAD

**Issue by jriwanek** [progwml6/Natura#243]
Mod packs would benefit from this, the first that comes to mind would be regrowth.

**Comment by Adaptivity** [comment]
I'll do this.

**Comment by progwml6** [comment]
feel free to disable recipes. I don't disable entire items.

**Comment by Adaptivity** [comment]
A lot of mods since 1.7.10 have config options to disable items. Check almost any mod and you'll find config options for disabling items. There are just no reason to not have them. If people want to disable them why we should stop them from that?

**Comment by progwml6** [comment]
i'm aware of them. Its not that simple with the 1.7 natura codebase has to just disable an item. Stuff like this is why we are rewriting from scratch for 1.8

**Comment by Adaptivity** [comment]
However, I've already made a config option for seed bags. Are you ok to merge this? That was pretty simple. At least we can add config options for stuff which was requested by people and not for every thing in 1.7.

**Comment by progwml6** [comment]
if you have the code i'll take a look.
my biggest concern is if addons are using the item or not.

**Comment by Adaptivity** [comment]
The only addon for Natura is Forestry as I can see. And it's not using seed bags. I'll create a PR soon.

**Comment by progwml6** [comment]
bibliocraft has some stuff also

**Comment by Adaptivity** [comment]
I don't think it's using seed bags :D
