### ISSUE TITLE
[Request] Restrict Nether worldgen to Nether only

### ISSUE THREAD

**Issue by Zsashas** [progwml6/Natura#251]
It seems that certain features, mainly the Thornvines, generate anywhere there is the Hell biome, even if it is outside of the Nether. Attached screenshot as an example (it's a Pocket Plane). The vines also don't care about actually being attached to anything, and often generate hanging in midair.
![2015-12-07_04 02 59](https://cloud.githubusercontent.com/assets/6917535/11628135/6f09083e-9ca4-11e5-808d-7c4cc5d9579d.png)

**Comment by progwml6** [comment]
see #109
