### ISSUE TITLE
Rendering crash natura+carpenters blocks

### ISSUE THREAD

**Issue by Saereth** [progwml6/Natura#255]
For some reason im getting a crash randomly as I explore, here is my crashlog
http://pastebin.com/qtXEYpMx

Not sure if this is a natura issue, CB issue or something completely unrelated

relevant information:
Minecraft version: 1.7.10
Forge: 1558
Nature: 1.7.10-2.2.1a2
Carpenter's Blocks: v3.3.7 - MC 1.7.10
client logfile:
https://drive.google.com/file/d/0BwmxXoRAG3ddZUN6aHBJbnlQVmc/view?usp=sharing

If I can provide any additional information I'll be glad to get it together for you, thanks

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
