### ISSUE TITLE
Leaf block ore dictionary crash

### ISSUE THREAD

**Issue by Reignofmagic** [progwml6/Natura#259]
Here is where I discovered the issue. My guess is you have the leaves oredictionaried with a wildcard which is not good. 

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/660#issuecomment-190378886

**Comment by Zsashas** [comment]
Is there a way to get the name of this wildcard block, so we can use MineTweaker to remove it from the ore dictionary?

**Comment by Barhandar** [comment]
The name is already known, it registers actual leaves but also some non-existent metadata. I've personally just removed all Natura leaves from oredict with MT (so I don't have to hunt in case it registers more than one), it's possible to append that to re-add ones that do exist.

**Comment by progwml6** [comment]
closing duplicate
