### ISSUE TITLE
Ticking Entity, Heatscar Spider Server crash. Bound must be positive?

### ISSUE THREAD

**Issue by Avarice** [progwml6/Natura#260]
We have Custom Mob Spawner, Infernal Mobs, Mo Creatures, and Special AI installed.
Heatscar Spiders were disabled in CMS, Infernal Mobs, and Special AI.
Ran a killall command and server still crashes.

> ---- Minecraft Crash Report ----
> // This doesn't make any sense!
> 
> Time: 29/02/16 20:10
> Description: Ticking entity
> 
> java.lang.IllegalArgumentException: bound must be positive
> 	at java.util.Random.nextInt(Random.java:388)
> 	at mods.natura.entity.HeatscarSpider.func_70106_y(HeatscarSpider.java:218)
> 	at net.minecraft.entity.EntityLiving.func_70623_bb(EntityLiving.java:512)
> 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:564)
> 	at net.minecraft.entity.EntityCreature.func_70626_be(SourceFile:91)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1780)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
> 	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:32)
> 	at net.minecraft.world.World.func_72866_a(World.java:2070)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
> 	at net.minecraft.world.World.func_72870_g(World.java:2034)
> 	at net.minecraft.world.World.func_72939_s(World.java:1887)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at java.util.Random.nextInt(Random.java:388)
> 	at mods.natura.entity.HeatscarSpider.func_70106_y(HeatscarSpider.java:218)
> 	at net.minecraft.entity.EntityLiving.func_70623_bb(EntityLiving.java:512)
> 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:564)
> 	at net.minecraft.entity.EntityCreature.func_70626_be(SourceFile:91)
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1780)
> 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
> 	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
> 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
> 	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
> 	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:32)
> 	at net.minecraft.world.World.func_72866_a(World.java:2070)
> 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
> 	at net.minecraft.world.World.func_72870_g(World.java:2034)
> 
> -- Entity being ticked --
> Details:
> 	Entity Type: Natura.FlameSpider (mods.natura.entity.HeatscarSpider)
> 	Entity ID: 13512
> 	Entity Name: Heatscar Spider
> 	Entity's Exact location: -58.50, 44.00, 73.50
> 	Entity's Block location: World: (-59,44,73), Chunk: (at 5,2,9 in -4,4; contains blocks -64,0,64 to -49,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1887)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
> 
> -- Affected level --
> Details:
> 	Level name: Overworld
> 	All players: 1 total; [EntityPlayerMP['Player'/5121, l='Overworld', x=59.15, y=80.96, z=35.88]]
> 	Chunk stats: ServerChunkCache: 581 Drop: 0
> 	Level seed: -3701366201688244304
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 0 game time, 0 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Linux (amd64) version 3.14.32-xxxx-std-ipv6-64-hz1000
> 	Java Version: 1.8.0_60, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 538929088 bytes (513 MB) / 1436291072 bytes (1369 MB) up to 6227755008 bytes (5939 MB)
> 	JVM Flags: 20 total; -Xincgc -XX:+UseParNewGC -XX:MaxPermSize=256M -XX:NewRatio=2 -XX:CMSFullGCsBeforeCompaction=1 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=2048 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -Xnoclassgc -Xoss4M -Xss4M -XX:+UseFastAccessorMethods -XX:CMSInitiatingOccupancyFraction=90 -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -Xmx6144M -Xms512M
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 85 mods loaded, 85 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614.jar) 
> 	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614.jar) 
> 	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
> 	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
> 	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
> 	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
> 	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
> 	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
> 	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
> 	UCHIJAAAA	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
> 	UCHIJAAAA	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
> 	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
> 	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
> 	UCHIJAAAA	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
> 	UCHIJAAAA	antiqueatlas{1.7.10-4.2.10} [Antique Atlas] (antiqueatlas-1.7.10-4.2.10.jar) 
> 	UCHIJAAAA	AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.7.10-1.3.0.jar) 
> 	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
> 	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
> 	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
> 	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
> 	UCHIJAAAA	BiblioWoodsNatura{1.3} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.3].jar) 
> 	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
> 	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
> 	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
> 	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
> 	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
> 	UCHIJAAAA	ForbiddenMagic{1.7.10-0.573} [Forbidden Magic] (Forbidden Magic-1.7.10-0.573.jar) 
> 	UCHIJAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
> 	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
> 	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
> 	UCHIJAAAA	BloodArsenal{1.2-4} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-4 (1).jar) 
> 	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
> 	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
> 	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
> 	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
> 	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
> 	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
> 	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
> 	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
> 	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
> 	UCHIJAAAA	examplemod{1.0} [examplemod] (ExtraDoors-1.7.2-1.5.1.jar) 
> 	UCHIJAAAA	extradoors{1.5.1} [Extra Doors] (ExtraDoors-1.7.2-1.5.1.jar) 
> 	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
> 	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
> 	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
> 	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
> 	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
> 	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
> 	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
> 	UCHIJAAAA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
> 	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
> 	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
> 	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
> 	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
> 	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
> 	UCHIJAAAA	MCA{1.7.10-5.1.1.2} [Minecraft Comes Alive] (MCA-1.7.10-5.1.1.2-universal.jar) 
> 	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
> 	UCHIJAAAA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
> 	UCHIJAAAA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
> 	UCHIJAAAA	neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
> 	UCHIJAAAA	Progression{0.4.1} [Progression] (Progression-1.7.10-0.4.1.jar) 
> 	UCHIJAAAA	Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-31.jar) 
> 	UCHIJAAAA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
> 	UCHIJAAAA	SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
> 	UCHIJAAAA	StorageDrawers{1.7.10-1.8.0} [Storage Drawers] (StorageDrawers-1.7.10-1.8.0.jar) 
> 	UCHIJAAAA	StorageDrawersMisc{1.7.10-1.1.2} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.1.2.jar) 
> 	UCHIJAAAA	StorageDrawersNatura{1.7.10-1.1.1} [Storage Drawers: Natura Pack] (StorageDrawers-Natura-1.7.10-1.1.1.jar) 
> 	UCHIJAAAA	TaintedMagic{1.1.6.4} [Tainted Magic] (TaintedMagic-1.1.6.4.jar) 
> 	UCHIJAAAA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
> 	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
> 	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
> 	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
> 	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
> 	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
> 	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
> 	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
> 	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
> 	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
> 	Mantle Environment: Environment healthy.
> 	TConstruct Environment: Environment healthy.
> 	Profiler Position: N/A (disabled)
> 	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	Player Count: 1 / 20; [EntityPlayerMP['Dom1nati0n'/5121, l='Nimbus Overworld', x=59.15, y=80.96, z=35.88]]
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server (map_server.txt)

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
