### ISSUE TITLE
Nitro creepers not following environmentallyFriendlyCreepers

### ISSUE THREAD

**Issue by Deckee** [progwml6/Natura#261]
The nitro Creepers are ignoring the codechickencore  environmentallyFriendlyCreepers=true config value.
A normal creeper will not brake blocks with this value Being true. Nitro creepers will brake blocks if the is true.
info
1.7.10 
FTB∞ evolved
 1.7.10-92.8a1150f

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
