### ISSUE TITLE
tainted soil and heat sand doesn't generate them with Biome O Plenty

### ISSUE THREAD

**Issue by Hypsellis** [progwml6/Natura#262]
Everything is in the title, they don't generate them when BoB is installed. The little nether shiny mushroom doesn't generate them either, while the big ones still generate them. The nether trees, bushes and big mushrooms tend to generate partially in the walls, ground, ceiling and under the lava.

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
