### ISSUE TITLE
Some natura leaves crash the client when viewed in recipes in NEI or Chromaticraft

### ISSUE THREAD

**Issue by notchriss** [progwml6/Natura#263]
Crash log: http://pastebin.com/17f4y5pw

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/830

MC 1.7.10

**Comment by ReikaKalseki** [comment]
Apparently there is a leaf variant - metadata 4 - being registered to the OreDict, yet it does not have a texture or name mapping. When NEI or the CC lexicon cycle to it...crash.

**Comment by Barhandar** [comment]
#259

**Comment by ReikaKalseki** [comment]
The thing is, it is not Short.MAX. There is an actual metadata-4 version being added.

**Comment by progwml6** [comment]
1.7 is no longer being updated. feel free to submit a PR.
