### ISSUE TITLE
Natura crashes Hardcore Ender Expansion with an NPE when adding items to its Instability Orb blacklist via IMC

### ISSUE THREAD

**Issue by Questwizard** [progwml6/Natura#265]
For some reason, Natura causes Hardcore Ender Expansion to crash with an NPE if using its IMC support to add items to the Instability Orb blacklist. Removing Natura fixes the issue. More details can be found here: chylex/Hardcore-Ender-Expansion#197

A full crashlog with only HEE, Mantle & Natura installed can be found here:
https://gist.github.com/Questwizard/95ac954c5d329d93b6661a0dc028523d

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
