### ISSUE TITLE
[1.10.2] ALPHA -- Things that need to be finished/fixed

### ISSUE THREAD

**Issue by alexbegt** [progwml6/Natura#267]
**Before Alpha**
`Needs fixing`
- [x]  Block/Item Names
- [ ] Bloodwood logs

`Needs to be added`
- [x] Ore Dictionary support
- [x] Crafting recipes (almost done)
- [x] Smelting Recipes
- [x] Finished config

`World Gen`
- [x] Overworld Trees 1 (Maple, Siverbell, Amaranth, Tiger)
- [x] Overworld Trees 2 (Willow, Eucalyptus, Sakura)
- [x] Overworld Trees 2 (Hopseed)
- [x] Overworld Berry Bushes
- [x] Nether Trees (Ghostwood, Fusewood, Darkwood)
- [ ] Nether Trees (Bloodwood) [World Gen Class needs to be made + blocks need to be added]
- [x] Nether Berry Bushes

`TESTING`
- [ ] Make sure it loads in SMP worlds and basic functionality works

**Comment by mgdgfbhevdyeh** [comment]
we getting a 1.10?

**Comment by progwml6** [comment]
@mgdgfbhevdyeh yes, this is the TODO list for the developers

**Comment by progwml6** [comment]
1st alpha released to curse see https://github.com/progwml6/Natura/issues/270 for alpha 2 list

**Comment by TheCandiedHat** [comment]
What was the problem with block/item names? And by checking it, do you mean it has been fixed?

**Comment by progwml6** [comment]
that was just setting up the language files initially
