### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by mightydanp** [progwml6/Natura#268]
I tried to do a build to test out the 1.10 version and i get this error
- Where:
  Build file 'C:\Users\chris\Desktop\Natura-1.10\build.gradle' line: 89
- What went wrong:
  A problem occurred evaluating root project 'natura'.
  
  > Cannot run program "git": CreateProcess error=2, The system cannot find the file specified

**Comment by progwml6** [comment]
you need to checkout from git instead of downloading the zip file
