### ISSUE TITLE
[1.10.2] [Bug] Bloodwood saplings appear upsidedown but plant on the top side of the block

### ISSUE THREAD

**Issue by SnowShock35** [progwml6/Natura#272]
Hello,

I believe to have found a bug with Natura for Minecraft 1.10.2, here are the details. . . 
### Important Information
- Minecraft 1.10.2 
- Minecraft Forge 12.18.1.2094
- Mantle 1.0.0
- Natura 1.10.2-4.0.0.72
### Issue Description

Pretty self explanatory in the title.
### Issue Media

![Issue Screenshot #1](http://ss.snowshock35.com/2016/09/1474903926-60dfc4f6.png)

**Comment by SnowShock35** [comment]
It's worth also noting that you cannot grow the trees because of this

**Comment by alexbegt** [comment]
This bug has been fixed, Please reopen a new ticket if this still continues to be a bug (over a year late lol)
