### ISSUE TITLE
[1.10.2] [Suggestion] [Beta] Chisel support for Natura

### ISSUE THREAD

**Issue by SnowShock35** [progwml6/Natura#278]
This would be very awesome to have down the line if not now perhaps in beta at somepoint I believe it's fairly simple to impliment with chisel but that's something that'd need to be discussed either with @Drullkus or @tterrag1098

**Comment by Drullkus** [comment]
I think @alexbegt might be the one to ask. It should be up to the Natura devs though. We've got tons of wood textures to do already on the table and Alex has porting on his plate. 

It's definitely an idea worth visiting though when both mods are more complete.

**Comment by progwml6** [comment]
I like the thought, we can discuss the details further down the line

**Comment by Drullkus** [comment]
https://minecraft.curseforge.com/projects/unlimited-chisel-works
