### ISSUE TITLE
(suggestion) new blocks, plants and mobs for the Ender

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#281]
Now that the Ender is an endless dimension like the Nether and Overworld, it would be awesome to add some new content to it, because for the time it looks really empty.

**Comment by progwml6** [comment]
Definitely worth looking into at some point

**Comment by 0Navis0** [comment]
Yeah it's sure. If you need some ideas, I have some. ;)

**Comment by 0Navis0** [comment]
I come back with that now since almost all the Natura content has been added back. I suppose it's the time to think about it. ;)
