### ISSUE TITLE
(suggestion) add NetherExtension mod content to Natura

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#285]
I just suggest that the content of this mod could be included in Natura for impoving a lot the Nether since this mod is dead and abandonned by their modders.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279248-the-nether-expansion-v0-3

**Comment by Zekken01** [comment]
I second this.

**Comment by TherminatorX** [comment]
See 
https://github.com/LogicTechCorp/NetherEx
and
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2654036-the-nether-expansion

**Comment by 0Navis0** [comment]
Sadly these bothe are pretty abandonned and include almost nothing from the original mod.

**Comment by TherminatorX** [comment]
@Hypsellis The latest commit was 3 days ago, and they're the same mod. It's a WIP to bring back that stuff. No need for Prog to do stuff someone else is working on.
