### ISSUE TITLE
[1.10.2-4.0.0.72]Crash when entering nether

### ISSUE THREAD

**Issue by Crazy-KSK** [progwml6/Natura#287]
http://pastebin.com/xZvvdP9V
I just build a nether portal and flew into it in creative, sadly the world now crashes on load so I can't tell you the coordinates of the portal.
Edit: Seems like just entering the nether anywhere does it on the world with seed 1

**Comment by 0Navis0** [comment]
It's normal, you don't use the last version. This crash has been already corrected on the new version.

**Comment by Crazy-KSK** [comment]
Welp
