### ISSUE TITLE
[1.10.2-4.0.0.76] Overworld decoration bugs

### ISSUE THREAD

**Issue by Crazy-KSK** [progwml6/Natura#288]
http://i.imgur.com/txsB76H.jpg 
Here some trees are growing too close to or inside each I have observed this happening with other tree types too  also one of them is missing its top most leave block.
http://i.imgur.com/6MggOlN.jpg
Here a tree is growing in a river, this also happens with other tree types.
http://i.imgur.com/easNAIv.jpg
I have also seen a berry bush grow inside  water.

**Comment by 0Navis0** [comment]
There is the same bugs with the nether trees and bushes which spawn in lava and/or partially in walls and ceiling.

**Comment by alexbegt** [comment]
Does any of this happen with 1.10.2-4.0.0.81?

**Comment by Crazy-KSK** [comment]
nether trees dark/fuse wood are still spawning in lava and the ground and walls 
https://i.imgur.com/4nAIjHt.jpg world seed 1

magma blocks may be spawning a bit too much don't know if that's intended ? 
https://i.imgur.com/O9Ir9yG.jpg 

maple and tiger trees still missing their tops 
https://i.imgur.com/78TFrYB.jpg

no water trees/bushes I could find so that seems to be fixed

**Comment by alexbegt** [comment]
@Crazy-KSK Isn't magma blocks vanilla minecraft?

**Comment by Crazy-KSK** [comment]
Yes...

**Comment by alexbegt** [comment]
All these bugs should be fixed with release of: natura-1.10.2-4.0.0.85.
