### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ArielFaye** [progwml6/Natura#289]
I crash repeatedly just after loading onto a server. Often crash randomly at times while traveling the world with the same error. No idea what is going on. My friend does not crash and is near the same spot. If you have any clue would be great. We are working an old 1.7.10 server magic theme. Thanks much for any help. Ariel M. Faye

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 9/27/16 4:29 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 13
    at mods.natura.blocks.overrides.AlternateBookshelf.func_149691_a(AlternateBookshelf.java:31)
    at net.minecraft.block.Block.func_149673_e(Block.java:556)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4666)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mods.natura.blocks.overrides.AlternateBookshelf.func_149691_a(AlternateBookshelf.java:31)
    at net.minecraft.block.Block.func_149673_e(Block.java:556)
    at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4666)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['ArielFaye'/207823, l='MpServer', x=-170.52, y=82.05, z=814.30]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-635,64,998), Chunk: (at 5,4,6 in -40,62; contains blocks -640,0,992 to -625,255,1007), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Level time: 24257148 game time, 26056706 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 101 total; [EntitySheep['Sheep'/207875, l='MpServer', x=-118.03, y=64.00, z=833.66], Entity_SpecialSpider['Spider'/207874, l='MpServer', x=-137.31, y=29.00, z=756.56], MoCEntityBunny['Bunny'/207873, l='MpServer', x=-209.50, y=78.00, z=782.00], EntityZombieCat['entity.GraveStone.GSZombieCat.name'/207872, l='MpServer', x=-209.50, y=39.00, z=775.50], Entity_SpecialZombie['Zombie'/207879, l='MpServer', x=-237.66, y=21.00, z=809.34], EntitySheep['Sheep'/207878, l='MpServer', x=-140.44, y=68.00, z=848.78], EntitySheep['Sheep'/207877, l='MpServer', x=-116.28, y=66.00, z=832.22], EntityClientPlayerMP['ArielFaye'/207823, l='MpServer', x=-170.52, y=82.05, z=814.30], EntitySheep['Sheep'/207876, l='MpServer', x=-117.41, y=65.00, z=832.47], Entity_SpecialZombie['Zombie'/207883, l='MpServer', x=-217.50, y=72.00, z=763.50], EntitySheep['Sheep'/207882, l='MpServer', x=-207.75, y=77.00, z=764.22], MoCEntityAnt['Ant'/207881, l='MpServer', x=-241.69, y=73.00, z=818.28], Entity_SpecialCreeper['Creeper'/207880, l='MpServer', x=-174.94, y=79.00, z=738.63], EntityZombie['Carl Maszom'/207887, l='MpServer', x=-118.03, y=12.00, z=761.38], Entity_SpecialCreeper['Creeper'/207886, l='MpServer', x=-215.53, y=72.00, z=761.56], Entity_SpecialZombie['Zombie'/207885, l='MpServer', x=-209.00, y=76.00, z=755.56], Entity_SpecialZombie['Zombie'/207884, l='MpServer', x=-213.72, y=74.00, z=769.16], EntityOcelot['Ocelot'/207891, l='MpServer', x=-204.38, y=78.00, z=870.00], MoCEntityDragonfly['DragonFly'/207890, l='MpServer', x=-121.88, y=64.00, z=753.59], Entity_SpecialSkeleton['Skeleton'/207889, l='MpServer', x=-118.72, y=64.00, z=753.84], EntityManaElemental['Mana Elemental'/207888, l='MpServer', x=-121.50, y=20.00, z=760.50], Entity_SpecialCreeper['Creeper'/207895, l='MpServer', x=-107.50, y=70.00, z=776.50], EntitySheep['Sheep'/207892, l='MpServer', x=-192.44, y=85.00, z=737.34], EntitySheep['Sheep'/207899, l='MpServer', x=-161.53, y=73.00, z=735.31], EntityZombieCat['entity.GraveStone.GSZombieCat.name'/207897, l='MpServer', x=-249.50, y=76.00, z=808.50], MoCEntityAnt['Ant'/207903, l='MpServer', x=-245.75, y=72.00, z=821.16], EntitySquid['Squid'/207902, l='MpServer', x=-128.50, y=58.31, z=748.50], MoCEntityBunny['Bunny'/207900, l='MpServer', x=-174.28, y=68.00, z=728.47], MoCEntityBird['Bird'/207907, l='MpServer', x=-155.63, y=68.00, z=885.84], MoCEntityAnt['Ant'/207904, l='MpServer', x=-254.59, y=78.00, z=818.13], MoCEntityFox['Fox'/207911, l='MpServer', x=-80.50, y=68.00, z=783.81], EntitySheep['Sheep'/207910, l='MpServer', x=-204.50, y=77.00, z=734.22], EntityChicken['Chicken'/207914, l='MpServer', x=-138.56, y=66.00, z=887.53], MoCEntityBird['Bird'/207912, l='MpServer', x=-90.78, y=72.00, z=834.22], EntitySheep['Sheep'/207923, l='MpServer', x=-243.50, y=67.00, z=752.55], EntitySheep['Sheep'/207922, l='MpServer', x=-243.50, y=66.00, z=753.55], MoCEntityDuck['Duck'/207920, l='MpServer', x=-210.56, y=81.00, z=886.75], Entity_SpecialZombie['Zombie'/207925, l='MpServer', x=-244.50, y=67.00, z=759.50], EntityHungryZombie['Hungry Zombie'/207924, l='MpServer', x=-240.50, y=65.00, z=759.03], MoCEntityBird['Bird'/207929, l='MpServer', x=-159.78, y=65.00, z=910.78], EntitySheep['Sheep'/207939, l='MpServer', x=-243.50, y=66.00, z=751.45], MoCEntityDuck['Duck'/207938, l='MpServer', x=-229.16, y=83.00, z=890.38], EntitySheep['Sheep'/207940, l='MpServer', x=-242.66, y=69.00, z=742.53], MoCEntityCricket['Cricket'/207947, l='MpServer', x=-85.53, y=67.00, z=874.75], MoCEntityBird['Bird'/207948, l='MpServer', x=-157.78, y=71.00, z=913.78], EntityZombie['Zombie'/1111, l='MpServer', x=0.10, y=-40.62, z=-4.40], EntityXPOrb['Experience Orb'/207963, l='MpServer', x=-247.31, y=32.25, z=695.22], MoCEntitySnake['Snake'/207961, l='MpServer', x=-80.81, y=72.00, z=897.16], MoCEntityButterfly['ButterFly'/207960, l='MpServer', x=-263.88, y=71.00, z=724.38], MoCEntityBird['Bird'/207967, l='MpServer', x=-83.66, y=64.22, z=912.22], EntitySpitfireSkeleton['Spitfire Skeleton'/208238, l='MpServer', x=-221.50, y=75.00, z=777.50], MoCEntityMouse['Mouse'/207991, l='MpServer', x=-53.47, y=72.00, z=917.56], MoCEntityCricket['Cricket'/208002, l='MpServer', x=-298.59, y=65.00, z=721.63], MoCEntityBird['Bird'/208000, l='MpServer', x=-64.72, y=70.00, z=939.22], Entity_SpecialCreeper['Creeper'/208275, l='MpServer', x=-226.13, y=82.00, z=891.66], Entity_SpecialZombie['Zombie'/208278, l='MpServer', x=-209.50, y=38.00, z=765.50], EntitySilverfish['Silverfish'/1941, l='MpServer', x=-19.48, y=-43.62, z=-43.17], EntityPlagueZombie['Plague Zombie'/208277, l='MpServer', x=-208.50, y=38.00, z=765.50], EntitySniperSkeleton['Sniper Skeleton'/208283, l='MpServer', x=-104.53, y=64.00, z=867.84], MoCEntityFirefly['Firefly'/208024, l='MpServer', x=-47.50, y=63.00, z=867.50], EntityPoisonSkeleton['Poison Skeleton'/208284, l='MpServer', x=-121.44, y=64.00, z=871.31], EntitySilverfish['Silverfish'/1730, l='MpServer', x=31.58, y=-38.71, z=35.45], EntitySheep['Sheep'/207835, l='MpServer', x=-150.25, y=78.00, z=805.59], Entity_SpecialZombie['Zombie'/207834, l='MpServer', x=-169.31, y=12.00, z=791.28], Entity_SpecialZombie['Zombie'/207833, l='MpServer', x=-171.30, y=11.02, z=784.28], EntitySheep['Sheep'/207839, l='MpServer', x=-156.45, y=78.00, z=817.45], EntitySheep['Sheep'/207838, l='MpServer', x=-157.53, y=79.32, z=818.53], EntityLightningCreeper['Lightning Creeper'/207837, l='MpServer', x=-154.50, y=74.00, z=792.50], EntitySheep['Sheep'/207836, l='MpServer', x=-158.38, y=80.00, z=831.47], EntityZombieCat['entity.GraveStone.GSZombieCat.name'/207843, l='MpServer', x=-205.41, y=39.00, z=778.03], EntitySheep['Sheep'/207842, l='MpServer', x=-153.47, y=73.00, z=844.63], EntitySheep['Sheep'/207841, l='MpServer', x=-145.50, y=76.00, z=847.50], EntitySheep['Sheep'/207840, l='MpServer', x=-148.50, y=77.00, z=843.50], EntitySheep['Sheep'/207847, l='MpServer', x=-202.53, y=86.00, z=777.50], EntitySheep['Sheep'/207846, l='MpServer', x=-213.47, y=75.00, z=771.63], EntityWebSpider['Web Spider'/207845, l='MpServer', x=-204.75, y=39.00, z=776.84], Entity_SpecialSpider['Spider'/207844, l='MpServer', x=-206.53, y=39.00, z=776.13], EntitySheep['Sheep'/207851, l='MpServer', x=-121.50, y=74.00, z=813.50], MoCEntityMouse['Mouse'/207850, l='MpServer', x=-209.88, y=78.00, z=808.31], EntityFireSkeleton['Fire Skeleton'/207849, l='MpServer', x=-129.34, y=26.00, z=771.22], EntitySheep['Sheep'/207848, l='MpServer', x=-201.47, y=86.00, z=777.50], Entity_SpecialCreeper['Creeper'/207855, l='MpServer', x=-179.50, y=14.00, z=759.50], EntityZombie['Ereulob Ditu'/207854, l='MpServer', x=-184.31, y=10.54, z=753.16], EntitySheep['Sheep'/207853, l='MpServer', x=-120.50, y=66.00, z=813.50], EntitySheep['Sheep'/207852, l='MpServer', x=-120.50, y=66.00, z=813.50], Entity_SpecialZombie['Zombie'/207859, l='MpServer', x=-188.34, y=17.00, z=756.31], Entity_SpecialZombie['Zombie'/207858, l='MpServer', x=-193.50, y=17.00, z=747.98], Entity_SpecialZombie['Zombie'/207857, l='MpServer', x=-188.66, y=17.00, z=757.22], Entity_SpecialSkeleton['Skeleton'/207856, l='MpServer', x=-189.56, y=14.00, z=774.06], Entity_SpecialZombie['Zombie'/207863, l='MpServer', x=-153.78, y=29.00, z=763.19], MoCEntityBunny['Bunny'/207862, l='MpServer', x=-186.06, y=77.00, z=768.13], EntityOcelot['Ocelot'/207861, l='MpServer', x=-177.50, y=75.00, z=754.06], Entity_SpecialZombie['Zombie'/207860, l='MpServer', x=-187.50, y=39.00, z=766.50], Entity_SpecialZombie['Zombie'/207867, l='MpServer', x=-113.38, y=62.00, z=790.78], MoCEntityMiniGolem['MiniGolem'/207866, l='MpServer', x=-113.22, y=62.00, z=789.13], MoCEntitySilverSkeleton['SilverSkeleton'/207865, l='MpServer', x=-114.50, y=62.00, z=790.53], MoCEntitySilverSkeleton['SilverSkeleton'/207864, l='MpServer', x=-115.06, y=62.00, z=788.47], EntitySheep['Sheep'/207871, l='MpServer', x=-104.16, y=63.00, z=824.81], EntitySheep['Sheep'/207870, l='MpServer', x=-122.50, y=79.00, z=816.50], Entity_SpecialZombie['Zombie'/207869, l='MpServer', x=-111.38, y=62.00, z=789.38], Entity_SpecialZombie['Zombie'/207868, l='MpServer', x=-113.59, y=62.00, z=791.81]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.11.6
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1084724184 bytes (1034 MB) / 2025848832 bytes (1932 MB) up to 2025848832 bytes (1932 MB)
    JVM Flags: 5 total; -Xms2048m -Xmx2048m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:PermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 52 mods loaded, 52 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCHIJA  CodeChickenCore{1.0.6.44} [CodeChicken Core](minecraft.jar) 
    UCHIJA  MobiusCore{1.2.3} [MobiusCore](minecraft.jar) 
    UCHIJA  NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UCHIJA  ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJA  AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJA  arsmagica2{1.4.0.009} [Ars Magica 2](1.7.10_AM2-1.4.0.009.jar) 
    UCHIJA  bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJA  ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    UCHIJA  DirectionHUD{1.24} [DirectionHUD]([1.7.10]DirectionHUD-client-1.24.jar) 
    UCHIJA  StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) 
    UCHIJA  BiblioCraft{1.11.5} [BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar) 
    UCHIJA  Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJA  Natura{2.2.0} [Natura](natura-1.7.10-2.2.1a2.jar) 
    UCHIJA  BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
    UCHIJA  BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHIJA  BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHIJA  AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJA  Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHIJA  ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UCHIJA  DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJA  MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
    UCHIJA  EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHIJA  ExtraUtilities{1.2.4c} [Extra Utilities](extrautilities-1.2.4c.jar) 
    UCHIJA  Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) 
    UCHIJA  ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-491.jar) 
    UCHIJA  ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](Forbidden Magic-1.7.10-0.562.jar) 
    UCHIJA  Forestry{4.2.15.63} [Forestry for Minecraft](forestry_1.7.10-4.2.15.63.jar) 
    UCHIJA  GraveStone{2.16.1} [GraveStone](GraveStone-2.16.1.jar) 
    UCHIJA  Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) 
    UCHIJA  Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) 
    UCHIJA  Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) 
    UCHIJA  Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) 
    UCHIJA  Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) 
    UCHIJA  Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
    UCHIJA  Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) 
    UCHIJA  Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) 
    UCHIJA  Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) 
    UCHIJA  inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJA  IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJA  JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) 
    UCHIJA  Mystcraft{0.12.3.02} [Mystcraft](mystcraft-1.7.10-0.12.3.02.jar) 
    UCHIJA  ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJA  SpecialMobs{3.2.2} [Special Mobs](SpecialMobs-1.7.10-3.2.2.jar) 
    UCHIJA  TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](TConstruct-1.7.10-1.8.5.jar) 
    UCHIJA  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJA  witchery{0.23.2} [Witchery](witchery-1.7.10-0.23.2.jar) 
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.10.13 310.42.25f01, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by progwml6** [comment]
1.7.10 is no longer supported
