### ISSUE TITLE
[1.10.2] Dedicated server crash

### ISSUE THREAD

**Issue by kwpugh** [progwml6/Natura#291]
Forge: 2095
Mod: natura-1.10.2-4.0.0.81.jar

Crash report: https://gist.githubusercontent.com/kwpugh/933f27f616f845736676b82085b0ec12/raw/a040c4868b5fba765aa44dd579e48e33915b9fa9/Natura

**Comment by progwml6** [comment]
@kwpugh can you provide the full forge log please
