### ISSUE TITLE
Your latest 1.10.2

### ISSUE THREAD

**Issue by MCTyler** [progwml6/Natura#294]
Your Latest update for 1.10.2 on curse downloads 1.7.10 version...I need the new file :)

**Comment by alexbegt** [comment]
That's because the latest download it get's is a release build, download it from https://minecraft.curseforge.com/projects/natura/files as it's still in a alpha state right now.

**Comment by MCTyler** [comment]
Thanks, I got it, just seemed weird that I clicked on 1.10.2 and got the version for 1.7.10. Great Mod! This was from the files tab on the curse website that specefically listed it as 1.10.2. Possibly a mixed up link perhaps?
