### ISSUE TITLE
List of Natura Tree Types

### ISSUE THREAD

**Issue by Stratzh** [progwml6/Natura#295]
I'm working on implementing a mod called Tree Chopper into my modpack and I need a list of the trees Natura adds in this format:

`tile.pamCinnamon`

I've looked around and can't find them. I'm probably blind and overlooked them somewhere. But if someone could point me in the right direction that would be really helpful and appreciated.

**Comment by TheCandiedHat** [comment]
This isn't exactly an issue within Natura... Think about looking for a better place to ask this question, please.
