### ISSUE TITLE
Berry Medley not able to be eaten after natura-1.10.2-4.0.0.81

### ISSUE THREAD

**Issue by WonderDog** [progwml6/Natura#297]
In natura-1.10.2-4.0.0.81 I can eat the Berry Medley if I am hungry. 

After updating to 4.0.0.86 I can no longer consume Berry Medley .  I get a funny aborted animation if I am Hungry and no animation if I am full.

Eating the Berryies themselves works even if I am not hungry in all versions.

I have also done some testing and it is not working in  4.0.0.85 either.

I am not sure but there may be an issure with the wooden bowls.  I started with 8 and now only have 3 and I dont know what happened to them.  I was only testing the Berry Medley in vesions 81, 85 and 86 and did not get any messeage about misssing blocks when loading the save.

**Comment by alexbegt** [comment]
natura-1.10.2-4.0.0.87.jar has this fix so you can eat the soups/berry medley again!
