### ISSUE TITLE
[1.10.2-4.0.0.87] No cotton & barley seed

### ISSUE THREAD

**Issue by ingratitude** [progwml6/Natura#300]
In survival Cotton seeds and barley do not spawn; and in Creative cotton seed, barley seeds are completely missing in inventory and search results are not showing for either of them (while Barley and Cotton itself can be found in Creative)

**Comment by progwml6** [comment]
we haven't implemented these yet

**Comment by alexbegt** [comment]
Cotton and barley now exist in natura-1.10.2-4.1.0.24!
