### ISSUE TITLE
some trees don't seem to spawn correctly

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#303]
I seems that some Natura trees don't spawn, even with same range and rarity than other trees which spawn everywhere. Sakura, Silverbell, Willow and Amaranth trees and some brush berries seems to have troubles to spawn correctly.

**Comment by progwml6** [comment]
what version?

**Comment by MCTyler** [comment]
1.10.2-4.0.0.87 will not retrogen Nether or spawn redwoods......Actually redwoods will not grow at all even with 5 stacks of bonemeal. :)

**Comment by 0Navis0** [comment]
The last version, and I know that some Nether trees and Redwood trees have still not been implemented yet.

**Comment by progwml6** [comment]
@MCTyler the redwood generator hasn't been implemented yet
nether retrogen is likely a seperate bug

when it comes to world generation bugs, the more specifics the better, and any screenshots of wierdness or world seeds help as well

**Comment by 0Navis0** [comment]
I have screenshots here because I these trees don't seem to spawn. I walked so far in the world and still didn't see any sakura trees, and just one willow ad two silverbell trees, while I see maple and tiger trees everywhere.

**Comment by alexbegt** [comment]
@Hypsellis Do you happen to have a world seed for one of the worlds that they don't spawn on?

**Comment by 0Navis0** [comment]
It would be useless, I play with with 195 mods. ^^'

**Comment by alexbegt** [comment]
@Hypsellis Alright, what type of berry bushes have issues generating?

**Comment by 0Navis0** [comment]
After having made more checks, it seems that berry bushes generate them well, it's more some trees which seem to have difficulties to generate them. I asked me if it's not linked to BiomesOPlenty presence which overwrite the vanilla biomes and add a lot of new biomes.

**Comment by 0Navis0** [comment]
Okay can I know in which biomes Natura trees are supposed to spawn, because they seem to spawn only in soma particular biomes like amaranth in jungles and willow in marshes.

**Comment by alexbegt** [comment]
Well natura trees should be spawning in any biome that has a biome type of Forest, Plains, Mountain & Hills, River, Jungle, Swamp, and of course Nether.

**Comment by 0Navis0** [comment]
It doesn't seem to be the case, they spawn only in particular biomes. Maple, Tiger and Silverbell in forests, Amaranth in jungles, Willow in marshes, Eucalyptus in mountains and plains , and I only see one sakura tree, so I don't know.

**Comment by progwml6** [comment]
@Hypsellis is this a particular modpack that you are using?

**Comment by alexbegt** [comment]
Oh whoops, I am tired so I made a mistake, certain trees grow in certain biomes: https://github.com/progwml6/Natura/blob/1.10/src/main/java/com/progwml6/natura/world/worldgen/TreeGenerator.java#L118-L266 for the overworld trees, https://github.com/progwml6/Natura/blob/1.10/src/main/java/com/progwml6/natura/world/worldgen/TreeGenerator.java#L287-L332 for nether trees. For the berry bushes, they don't really go by biomes

**Comment by 0Navis0** [comment]
This is my own modpack, I still didn't submit it. ^^'

**Comment by 0Navis0** [comment]
I think it's a problem with other mods which modify a lot the world generation like BOP, AbyssalCraft, Reccurent Complex...

**Comment by 0Navis0** [comment]
I have stil not been able to see hopeseed trees, I suppose they spawn only in particular biomes.

**Comment by 0Navis0** [comment]
I confirm that Hopeseed trees don't spawn at all.

**Comment by alexbegt** [comment]
If you find any other issues with trees/bushes not generating, please feel free to reopen this issue, or make a new one :) @Hypsellis

**Comment by 0Navis0** [comment]
Ghostwood and nether trees in general seems to have difficulties to spawn too.
