### ISSUE TITLE
Bug with Sakura trees

### ISSUE THREAD

**Issue by Terloc** [progwml6/Natura#304]
How I can fix that?

![2016-11-04_01 37 49](https://cloud.githubusercontent.com/assets/23220362/19993813/a10cf82c-a22f-11e6-85d3-151a844bf292.png)

**Comment by alexbegt** [comment]
What do you mean by "bun with sakura trees"?

**Comment by alexbegt** [comment]
@Terloc What mods do you have installed?

**Comment by Drullkus** [comment]
Looks like it's an issue with Better Foliage... And it's written in Kotlin.

@octarine-noise any idea why this is happening?

**Comment by Zekken01** [comment]
What's the eta on this?

**Comment by progwml6** [comment]
@brodycas3 we don't give etas for individual fixes

**Comment by Zekken01** [comment]
ok, do you have an eta for the next update?

**Comment by alexbegt** [comment]
This is not natura's fault, It is Better Foliage who needs to update to support natura's 1.10's way of doing logs.

**Comment by octarine-noise** [comment]
That is correct. I'll get it done, but I also can't give an ETA for the next release.

**Comment by alexbegt** [comment]
This bug has been fixed by Better Foliage.
