### ISSUE TITLE
Better foliage support

### ISSUE THREAD

**Issue by Zekken01** [progwml6/Natura#306]
It would seem that your logs refuse to want to work with better foliage.
As you can see logs from other mods such as Forestry and Biomes O' Plenty work fine.
If you could please add support. https://minecraft.curseforge.com/projects/better-foliage
http://i.imgur.com/TsNMPFK.png

**Comment by Zekken01** [comment]
Added a new Imgur link since I messed that one up somehow and spruced up the text a bit.

**Comment by progwml6** [comment]
see #304
