### ISSUE TITLE
[1.10.2-4.0.0.93] Nether trees and bushes don't generate in NetherEx biomes

### ISSUE THREAD

**Issue by seanianjones** [progwml6/Natura#307]
Forge-12.18.2.2151
NetherEx-1.1.0

NetherEx adds new biomes to the nether that none of Natura's plants generate in.

**Comment by seanianjones** [comment]
![2016-11-19_15 41 25](https://cloud.githubusercontent.com/assets/1068442/20458290/c75c51ee-ae6e-11e6-86d3-f4543bbcd4fd.png)

After looking around for a few more hours I've found a berry bush, but still no trees.

**Comment by 0Navis0** [comment]
NetherEx is currently in a state of totally rewritting, the mod isn't more the same and the last version on Curse is totally obsolete.

**Comment by alexbegt** [comment]
Hi There,

If this does still occur, please open a new issue report!

Thanks!

**Comment by 0Navis0** [comment]
No it doesn't happen more since NetherEx has been totally rewritten. Otherwise another issue happens which is from NetherEx side. The mobs from other mods than NetherEx don't spawn in the nether.
