### ISSUE TITLE
Leaf decay glitch

### ISSUE THREAD

**Issue by Mlmiii** [progwml6/Natura#309]
Cutting down a natura tree does not cause the leaves to decay if a log block is within a few blocks. I'd assume this is due to the "Only decay when not within X distance of a log block" code only checking distance and not whether or not those leaves are actually attached to the tree. This is entirely understandable on Redwoods but a little annoying on the smaller trees.

**Comment by alexbegt** [comment]
What version of minecraft are you on?

**Comment by Mlmiii** [comment]
1.7.10

**Comment by TherminatorX** [comment]
1.7.10 is no longer receiving updates, open a new report if it happens in current versions.
