### ISSUE TITLE
Issue - Redwood Won't Grow [1.10.2]

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [progwml6/Natura#315]
Exactly what the title says; Redwood won't grow. Period. Which is the whole reason I had this mod. :(

**Comment by P3rf3ctXZer0** [comment]
![2017-01-09_23 46 34](https://cloud.githubusercontent.com/assets/10351221/21795279/8d141ac8-d6c6-11e6-9e84-8500462ab8df.png)

**Comment by LovelyFlare** [comment]
Duplicate of #313

**Comment by progwml6** [comment]
natura redwoods don't grow as a 1x1 and they also haven't been implemented for 1.10.2 yet

**Comment by P3rf3ctXZer0** [comment]
@progwml6 thank you for the information. Let me know when you add them.
