### ISSUE TITLE
Berries can still be eaten even if saturation is filled

### ISSUE THREAD

**Issue by MastaC729** [progwml6/Natura#316]
I remember in old versions when you ate berries that you would stop eating them when you reached full saturation. Was this intentionally removed, or is this a bug?

**Comment by simbacaned** [comment]
This is not a bug, since 1.6.4 you could eat berries once you had full hunger, but, once again, it would just fill saturation, they would have patched it since then, I think :)

**Comment by MastaC729** [comment]
No, what I am saying is that even at full saturation you can continue to eat them. I'm sure you're aware that saturation is different from hunger, and in this case I mean saturation.

**Comment by MastaC729** [comment]
Not sure if you guys intentionally did this, but now berries cannot take you to full saturation. They can take you to full hunger, just not full saturation.

**Comment by alexbegt** [comment]
That is vanilla related, Vanilla does not check the Saturation level when you check if the player needs to eat some food.
