### ISSUE TITLE
Redwood trees do NOT grow, with or without bone meal.

### ISSUE THREAD

**Issue by eyeonus** [progwml6/Natura#317]
I don't know if it's a mod conflict with something in Direwolf20's 1.10.2 modpack, but I've already looked into the config with no luck.

Redwood trees do NOT grow. At all. I've tried bone meal with no results, and I've had a 7x7 just sitting there for a real world week with the server running the whole time, and no redwoods at all.

This is with natura-1.10.2-4.1.0.17, although I was also having the same issue with the previous couple version as well.

**Comment by progwml6** [comment]
redwoods aren't fully coded yet in 1.10.2

**Comment by eyeonus** [comment]
That explains it. Let me know when they are?
