### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ghost** [progwml6/Natura#318]
please update this amazing mod to 1.11.2 plzz

**Comment by 0Navis0** [comment]
This isn't the place for giving putting this kind of messages, the modders do their best for updating and improving their mods, but they have a life and can't work always on their mods. 
Natura is still incomplete, so for the time they will surely reintegrate all the missing content before to think to update it for 1.11.2. 
So if you want to help them, participate to the developpment or report issue, but don't send this kind of comments, it's just annoying.

**Comment by progwml6** [comment]
We are planning on getting a few more features into 1.10.2 before we go up to 1.11
