### ISSUE TITLE
[1.10.2] Nether vines facing/orientation is random

### ISSUE THREAD

**Issue by DeadSix27** [progwml6/Natura#322]
Version: https://github.com/progwml6/Natura/commit/e49ebd342fda3e00812e8396d3cc0ebb015dc127

Is this a bug or intentionally?

![2017-02-25_15 27 34](https://cloud.githubusercontent.com/assets/1492505/23331879/f4c3d560-fb6e-11e6-8bcc-ab55f837f8c4.png)

**Comment by alexbegt** [comment]
Thanks for the bug report, It was a bug as in 1.7 that didn't happen!
