### ISSUE TITLE
Clarification for Which Saplings Now Correctly Grow

### ISSUE THREAD

**Issue by Darkosto** [progwml6/Natura#325]
I believe I may have misunderstood some information about the latest update of the mod, are all trees except for Bloodwoods now working correctly?

As a test, I went through and tried to grow a number of saplings and was unable to grow more than 4 trees total. 

Any information you may have would be appreciated, thank you!
Darkosto

**Comment by alexbegt** [comment]
Yes all saplings besides bloodwood _should_ grow, and what trees did not want to grow?

**Comment by Darkosto** [comment]
So far, I've been able to grow:
Eucalyptus, Redwood, Sakura, 

Saplings I've tried but have not been able to grow:
Hopseed, Maple, Willow, Darkwood, Tigerwood, Silverbell, and Amaranth

Natura Version: 4.1.0.24

Edit: I assume they should grow in a ForestHills biome? I've tried single saplings, 2x2, 3x3, 4x4 just to make sure I set them up correctly.

**Comment by alexbegt** [comment]
If you are setting up a sky block world, you might need to change the "Sea Level" value in the config to be lower then 64, so what I would do is, check what Y level you are at and subtracting 10 from the value, so if the Y level is 60, subtract 10 and make "Sea Level" equal to 50.
