### ISSUE TITLE
Barley/wheat flour recipe missing

### ISSUE THREAD

**Issue by Renadarain** [progwml6/Natura#326]
Hi :)

Barley and barley seeds are spawning in the world but the recipe is missing or broken.  Barley and seeds are set to "true" in the config file.  

Am I jumping the gun and the recipe hasn't been implemented as yet?

Regards,
Renada

**Comment by alexbegt** [comment]
Hi there Renada!

Thanks for the report! The recipe is not added yet, but it will be added today!

Thanks,
Alexander (Alexbegt)

**Comment by Renadarain** [comment]
Thank you :)

**Comment by SmallSansSerif** [comment]
Any update on this?

**Comment by Lethann** [comment]
We just started our server today and it's still not in. Any word?

**Comment by TheCandiedHat** [comment]
I've been playing FTB Beyond with Natura, and it seems to work for me... I can make wheat and barley flour, and NEI and JEI say the recipes are there. Can this issue please be closed?

**Comment by alexbegt** [comment]
This has been added and pushed to the newest versions of Natura!
