### ISSUE TITLE
Missing Mods: Waila: [1.8.8]

### ISSUE THREAD

**Issue by zISKo666** [progwml6/Natura#333]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.298.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.1.1.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.205-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  CorePlugin (MrTJPCore-1.10.2-2.0.0.14-universal.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  MalisisSwitchesPlugin (malisisswitches-1.10.2-3.2.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  PlayerAPIPlugin (PlayerAPI-1.10.2-1.1.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.5.97-universal.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 4/2/17 8:22 AM
Description: Exception in server tick loop

Missing Mods:
	Waila : [1.8.8,)

net.minecraftforge.fml.common.MissingModsException: Mod natura (Natura) requires [Waila@[1.8.8,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:285)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.4.26-nitradoV3-MC-1000-nH-dP-d-i
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 394014184 bytes (375 MB) / 1248854016 bytes (1191 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6144M -Xms256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 168 mods loaded, 168 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (minecraft_server.jar) 
	U	Forge{12.18.3.2254} [Minecraft Forge] (minecraft_server.jar) 
	U	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	U	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	U	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	U	NotEnoughItems{2.1.3.205} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.205-universal.jar) 
	U	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	U	PlayerAPI{1.1} [Player API] (minecraft.jar) 
	U	backpacks16840{3.1.5} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.5.jar) 
	U	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	U	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	U	advancedRocketry{1.10.2-1.1.1} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.1.1.jar) 
	U	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	U	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	U	AppleCore{2.1.2} [AppleCore] (AppleCore-mc1.10.2-2.1.2.jar) 
	U	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	U	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	U	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	U	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar) 
	U	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	U	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	U	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	U	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	U	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	U	BloodArsenal{1.10.2-2.0.1-17} [Blood Arsenal] (BloodArsenal-1.10.2-2.0.1-17.jar) 
	U	BloodMagic{1.10.2-2.1.8-77} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.8-77.jar) 
	U	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	U	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	U	brandonscore{2.1.5} [Brandon's Core] (BrandonsCore-1.10.2-2.1.5.97-universal.jar) 
	U	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	U	CharsetLib{0.3.4} [â€½] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	CharsetPipes{0.3.4} [|] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	CharsetTweaks{0.3.4} [*] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	CharsetAudio{0.3.4} [â™«] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	CharsetStorage{0.3.4} [#] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	CharsetDecoration{0.3.4} [^] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	CharsetWrench{0.3.4} [/] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	U	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	U	chisel{MC1.10.2-0.0.9.15} [Chisel] (Chisel-MC1.10.2-0.0.9.15.jar) 
	U	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	U	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	U	CodeChickenLib{2.5.7.241} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	U	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.7.241-universal.jar) 
	U	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	U	commoncapabilities{1.3.1} [CommonCapabilities] (CommonCapabilities-1.9.4-1.3.1.jar) 
	U	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0.jar) 
	U	covers{0.4.1.17} [Simple Covers] (covers-0.4.1.17-mc1.10.2.jar) 
	U	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	U	cyclicmagic{1.10.17} [Cyclic] (Cyclic-1.10.2-1.10.17.jar) 
	U	cyclopscore{0.10.0} [Cyclops Core] (CyclopsCore-1.9.4-0.10.0.jar) 
	U	darkutils{1.1.7.120} [Dark Utilities] (DarkUtilities-1.10.2-1.1.7.120.jar) 
	U	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	U	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	U	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	U	draconicevolution{2.0.9} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.9.189-universal.jar) 
	U	bitdrawers{0.36} [Drawers & Bits] (DrawersBits-1.10.2-0.36.jar) 
	U	eleccore{1.7.409} [ElecCore] (ElecCore-1.10.2-1.7.409.jar) 
	U	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	U	embers{0.104} [Embers] (embers-0.104.jar) 
	U	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	U	EnderIO{1.10.2-3.1.179} [Ender IO] (EnderIO-1.10.2-3.1.179.jar) 
	U	EnderStorage{2.2.1.103} [EnderStorage] (EnderStorage-1.10.2-2.2.1.103-universal.jar) 
	U	endertanks{1.4.11} [EnderTanks] (endertanks-1.10.0-1.4.11.jar) 
	U	enderthing{0.7.3} [Enderthing] (enderthing-1.10.2-0.7.3.jar) 
	U	enderutilities{0.6.7} [Ender Utilities] (enderutilities-1.10.2-0.6.7.jar) 
	U	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	U	energysynergy{1.1.1} [EnergySynergy] (EnergySynergy-1.10.2-1.1.1.jar) 
	U	ExtraBitManipulation{1.10.2-2.3.3} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.3.3.jar) 
	U	golems{6.02} [Extra Golems] (ExtraGolems[1.10.2]-6.02.jar) 
	U	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	U	bigreactors{1.10.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.27.jar) 
	U	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	U	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	U	fluxnetworks{1.2.0} [FluxNetworks] (FluxNetworks-1.10.2-1.2.0.jar) 
	U	forestry{5.2.17.368} [Forestry] (forestry_1.10.2-5.2.17.368.jar) 
	U	microblockcbe{2.0.0.29} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	U	forgemultipartcbe{2.0.0.29} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	U	minecraftmultipartcbe{2.0.0.29} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.29-universal.jar) 
	U	gearswap{1.4.1} [Gear Swapper] (gearswap-1.1x-1.4.1.jar) 
	U	gendustry{1.6.5.30} [GenDustry] (gendustry-1.6.5.30-mc1.10.2.jar) 
	U	advgenerators{0.9.20.23} [Advanced Generators] (generators-0.9.20.23-mc1.10.2.jar) 
	U	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	U	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	U	ichunutil{6.2.0} [iChunUtil] (iChunUtil-1.10.2-6.2.0.jar) 
	U	IGWMod{1.3.0-5} [In-Game wiki Mod] (IGW-Mod-1.9.4-1.3.0-5-universal.jar) 
	U	immcraft{1.3.1} [Immersive Craft] (immcraft-1.1x-1.3.1.jar) 
	U	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	U	integrateddynamics{0.6.11} [Integrated Dynamics] (IntegratedDynamics-1.10.2-0.6.11.jar) 
	U	inventorysorter{0.11.0+47} [Simple Inventory sorting] (inventorysorter-1.10.2-0.11.0+47.jar) 
	U	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	U	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	U	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	U	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	U	libVulpes{0.2.0.20170307012613} [libVulpes] (LibVulpes-1.10.2-0.2.0-universal.jar) 
	U	limelib{1.3.5} [LimeLib] (limelib-1.10.2-1.3.5.jar) 
	U	magneticraft{@VERSION@} [Magneticraft] (magneticraft-1.0.2-release.jar) 
	U	malisisblocks{1.10.2-4.2.0} [Malisis Blocks] (malisisblocks-1.10.2-4.2.0.jar) 
	U	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	U	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	U	malisisswitches{1.10.2-3.2.0} [Malisis Switches] (malisisswitches-1.10.2-3.2.0.jar) 
	U	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	U	Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.298.jar) 
	U	MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.1.298.jar) 
	U	MekanismTools{9.2.1} [MekanismTools] (MekanismTools-1.10.2-9.2.1.298.jar) 
	U	moarsigns{4.2.2.8} [MoarSigns] (MoarSigns-1.10.2-4.2.2.8.jar) 
	U	mobamputation{6.0.0} [MobAmputation] (MobAmputation-1.10.2-6.0.0.jar) 
	U	mob_grinding_utils{0.1.8.16} [mob_grinding_utils] (MobGrindingUtils-0.1.8.16.jar) 
	U	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	U	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	U	MrTJPCoreMod{2.0.0.14} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.14-universal.jar) 
	U	multistorage{1.2.16} [Multi-Storage] (multistorage-1.10.0-1.2.16.jar) 
	U	natura{1.10.2-4.1.0.29} [Natura] (natura-1.10.2-4.1.0.29.jar) 
	U	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	U	nice{0.1.0} [Nice] (nice-0.1.0.jar) 
	U	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	U	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	U	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	U	platforms{1.2.9} [Platforms] (platforms-1.10.0-1.2.9.jar) 
	U	pressure{1.3.1.25} [Pressure Pipes] (pressure-1.3.1.25-mc1.10.2.jar) 
	U	projectred-core{4.8.1.25} [ProjectRed Core] (ProjectRed-1.10.2-4.8.1.25-Base.jar) 
	U	projectred-integration{4.8.1.25} [ProjectRed integration] (ProjectRed-1.10.2-4.8.1.25-integration.jar) 
	U	projectred-transmission{4.8.1.25} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.1.25-integration.jar) 
	U	projectred-illumination{4.8.1.25} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.1.25-lighting.jar) 
	U	projectred-expansion{4.8.1.25} [ProjectRed Expansion] (ProjectRed-1.10.2-4.8.1.25-mechanical.jar) 
	U	projectred-tansportation{1.0} [projectred-tansportation] (ProjectRed-1.10.2-4.8.1.25-mechanical.jar) 
	U	projectred-exploration{4.8.1.25} [ProjectRed Exploration] (ProjectRed-1.10.2-4.8.1.25-world.jar) 
	U	quantumflux{2.0.11} [QuantumFlux] (quantumflux-1.10.2-2.0.11.jar) 
	U	quantumstorage{3.3.1} [QuantumStorage] (QuantumStorage-1.10.2-3.3.1.jar) 
	U	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	U	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	U	reborncore{2.13.5.136} [RebornCore] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	U	reborncore-mcmultipart{2.13.5.136} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.5.136-universal.jar) 
	U	redstonearsenal{2.0.3} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.0.3.29-universal.jar) 
	U	refinedstorage{1.2.25} [Refined Storage] (refinedstorage-1.2.25.jar) 
	U	xreliquary{1.10.2-1.3.3.639} [Reliquary] (Reliquary-1.10.2-1.3.3.639.jar) 
	U	rflux{0.1.0} [RF Lux] (rflux-0.1.0.jar) 
	U	rftools{5.91} [RFTools] (rftools-1.1x-5.91.jar) 
	U	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	U	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	U	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	U	roots{0.015} [Roots 2] (roots-2-0.015.jar) 
	U	routerreborn{1.10.2-4.0.1.24_universal} [Router Reborn] (RouterReborn-1.10.2-4.0.1.24_universal.jar) 
	U	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	U	shetiphiancore{3.3.8} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.8.jar) 
	U	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-1-10.2-0.0.3.jar) 
	U	sonarcore{3.2.6} [SonarCore] (SonarCore-1.10.2-3.2.6.jar) 
	U	StorageDrawers{1.10.2-3.6.3} [Storage Drawers] (StorageDrawers-1.10.2-3.6.3.jar) 
	U	storagenetwork{2.0.9} [StorageNetwork] (storagenetwork-2.0.9.jar) 
	U	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	U	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	U	theoneprobe{1.4.5} [The One Probe] (theoneprobe-1.1x-1.4.5.jar) 
	U	thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90-universal.jar) 
	U	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	U	thutcore{3.12.1} [ThutCore] (thutcore-3.12.1.jar) 
	U	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.10.b.jar) 
	U	tinker_io{release 2.4.3} [Tinker I/O] (tinker_io-1.10.2-release 2.4.3.jar) 
	U	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	U	Translocator{2.1.4.54} [Translocator] (Translocators-1.10.2-2.1.4.54-universal.jar) 
	U	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	U	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	U	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	U	xnet{1.1.4} [XNet] (xnet-1.1.4.jar) 
	U	xtones{1.10.2-1.0.1-3} [Xtones] (Xtones-1.10.2-1.0.1-3.jar) 
	U	zerocore{1.10.2-0.1.0.4} [Zero CORE] (zerocore-1.10.2-0.1.0.4.jar) 
	U	Zoology{1.0} [Zoology] (zoology-1.10-alpha-1.0.1.jar) 
	U	zoom{1.1.0} [Zoom] (Zoom-MC1.10.2-1.1.0.jar) 
	U	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
LoadingHook (Mekanism-1.10.2-9.2.1.298.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.1.1.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.205-universal.jar)
  codechicken.nei.asm.NEITransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
CorePlugin (MrTJPCore-1.10.2-2.0.0.14-universal.jar)
  
AppleCore (AppleCore-mc1.10.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.10.2-3.2.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
PlayerAPIPlugin (PlayerAPI-1.10.2-1.1.jar)
  api.player.forge.PlayerAPITransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.5.136-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  team.chisel.common.asm.ChiselTransformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
Brandon's Core (BrandonsCore-1.10.2-2.1.5.97-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
  brad16840.common.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.8.jar)
  shetiphian.core.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by vrork** [comment]
Same here, even tough i have the latest avaible waila version

**Comment by alexbegt** [comment]
It's due to me removing Waila support and switching to Hwyla, the 1.8.8 is the version number of Hwyla (A fork of Waila)

**Comment by vrork** [comment]
Dont do that. Keep support for both. Otherwise yours is gonna be only mod that uses hwyla.

**Comment by alexbegt** [comment]
It's hard to support both as Hwyla uses the same plugin service as Waila, I'll just switch back the other support until 1.11.

**Comment by zISKo666** [comment]
Thank you for your quick response.

**Comment by alexbegt** [comment]
Natura-4.1.0.34 will fix this issue!
