### ISSUE TITLE
Natura 1.10.2-4.1.0.29 needs waila 1.8.8 or higher

### ISSUE THREAD

**Issue by jusitnboggs** [progwml6/Natura#336]
Natura 1.10.2-4.1.0.29 needs waila 1.8.8 or higher and I have waila for 1.10.2 which is 1.9.4

I went back to natura 1.0.24 and it works just fine

**Comment by Rudy2D2** [comment]
Same here.

**Comment by alexbegt** [comment]
Natura-4.1.0.34 will fix this issue!
