### ISSUE TITLE
Possible Crash due to Natura Clouds (Exception getting block type)

### ISSUE THREAD

**Issue by Gamerbolts** [progwml6/Natura#338]
Hi I am building a modpack and I had a user who was testing for me and she was roaming around the world and the server crashed I checked out the crash log, posted below, and it looks like it has something to do with the cloud gen. Would simply turning off ash and dark cloud gen work? Please let me know. Thanks

https://pastebin.com/TJ2dwQ1m

**Comment by progwml6** [comment]
1.7.10 is no longer supported
