### ISSUE TITLE
Redwood Saplings spread?

### ISSUE THREAD

**Issue by Darianna77** [progwml6/Natura#340]
Hello, in 1.10.2....have plantet Redwood Saplings in a 7x7 Field and then i have 2 Redwoods side on side and many saplings spare around they...
I love Redwood and cant find one in the World (wont they generate /grow normally in the world? ) so i would like to plant one by myself...
But with these spread its...trycky...i need one....not many that broke my world ;)

**Comment by alexbegt** [comment]
What version of Natura are you running?

**Comment by Darianna77** [comment]
In Beyond... 4.1.0.34

**Comment by CovertJaguar** [comment]
Combine with Auto Sapling and you will find that Redwoods will take over your entire world like some kind of curse of nature.

**Comment by alexbegt** [comment]
natura-1.10.2-4.1.0.48 has the fix and is uploading to curseforge!
