### ISSUE TITLE
Dimension Blacklist for Natura Gen

### ISSUE THREAD

**Issue by Utildayael** [progwml6/Natura#341]
Perhaps I'm missing it in the config and if so, I apologize!

Is there a way to blacklist an entire dimension from getting Natura generation? For example, I want to blacklist dim 6 [Aroma's Mining Dimension] from getting any Natura stuff. It currently generates Hopseed and Eucalyptus trees as well as berry bushes.

Thanks :)

**Comment by Utildayael** [comment]
Thank you sir!

**Comment by alexbegt** [comment]
natura-1.10.2-4.1.0.53 has this!

**Comment by Utildayael** [comment]
Thank you sir! Saw the commit. Thanks for the quick fix. :)

**Comment by tjeulink** [comment]
What is the proper syntax for blacklisting dimensions? i tried this syntax:
```
 I:"dimension blacklist(ash clouds)" <
   -2,0,1,2,3,4,5,6,7,8,9,10
   >`
```

but it just removes it from the config file upon loading it. Is this a bug? I can't find any documentation.
