### ISSUE TITLE
REDWOOD SAPLINGS EVERYWHERE!

### ISSUE THREAD

**Issue by ArtOfCombat** [progwml6/Natura#342]
I planted a 7x7 of redwood saplings in the attobitus branch of infinity beyond in creative... and they spread like wildfire. And grew. And destroyed parts of the spawn for my server. These saplings should not spread, something is wrong.

**Comment by ArtOfCombat** [comment]
Natura version is 4.1.0.34 for 1.10.2.

**Comment by alexbegt** [comment]
Same as #340, Please download version 4.1.0.48 for 1.10.2 for the fix.
