### ISSUE TITLE
small glowshrooms don't spawn in the nether

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#344]
The glowshrooms only spawn in big version and not in small version as they did on 1.7.10 version. I had a suggestion too to make spawn big version of red and brown mushrooms.

**Comment by capt-slowpoke** [comment]
They are not producing any light for me, are they working for you?

**Comment by 0Navis0** [comment]
Oh it's right they don't do.

**Comment by alexbegt** [comment]
In 1.7.10, the only time the small glowshrooms spawned in the nether was when you had the nether being overwritten by the Netherite dim.

**Comment by alexbegt** [comment]
natura-1.10.2-4.1.0.53 has this!
