### ISSUE TITLE
Darkwood trees dropping unusuable saplings

### ISSUE THREAD

**Issue by capt-slowpoke** [progwml6/Natura#345]
Harvesting darkwood leaves is dropping a sapling with a broken black and purple texture graphic that's named "Ghostwood sapling" and has the ghostwood sapling's description. When it's planted on netherrack a ghostwood sapling is planted. Darkwood saplings given through console or creative mode mode work properly. 

MC 1.10.2
Natura 4.1.0.34
Forge 12.18.3.2185

**Comment by alexbegt** [comment]
natura-1.10.2-4.1.0.53 has this!
