### ISSUE TITLE
[1.10.2][Bug] Bloodwood Trees dropping Fusewood Spalings

### ISSUE THREAD

**Issue by Compegen** [progwml6/Natura#348]
Using version `1.10.2-4.1.0.53`
__________
When mining Bloodwood leaves, they drop Fusewood Saplings instead of their proper type.

**Comment by capt-slowpoke** [comment]
Can confirm this, I'm getting the same. Fusewood is dropping the wrong saplings also.

**Comment by Utildayael** [comment]
Also confirmed.
