### ISSUE TITLE
1.10.2 [bug] Potash apples unharvestable

### ISSUE THREAD

**Issue by capt-slowpoke** [progwml6/Natura#350]
Darkwood apples aren't harvestable by right clicking the leaf block or by breaking it. 

MC 1.10.2 
natura 4.1.0.53

**Comment by alexbegt** [comment]
Potash Apples are obtained like regular apples, they drop when the leaf block is broken, but the leaf needs to have white circles on them.

**Comment by capt-slowpoke** [comment]
Do they not always drop even if the leaf block has them on it?
