### ISSUE TITLE
Bloodwood grows in spectre dimension?!?

### ISSUE THREAD

**Issue by NicosaurusRex99** [progwml6/Natura#357]
Natura's bloodwood spawns in 1.11.2.
http://imgur.com/a/CJAsc

**Comment by NicosaurusRex99** [comment]
@lumien231 i think this is also related to you if you author random things

**Comment by lumien231** [comment]
Yeah, i currently use the Hell Biome in the Spectre Dimension. Gonna change it to a custom Biome next version :).

**Comment by NicosaurusRex99** [comment]
Thanks, ETA?!? im making a pack
