### ISSUE TITLE
Bloodwood trees are 1 layer only

### ISSUE THREAD

**Issue by nohelix** [progwml6/Natura#360]
When growing bloodwood trees upside down on netherrack (at y=62) I get a one block thick 2x2 trunk at y=0. This occurs in both the nether and the overworld. Growth was accelerated with bone-meal. To be clear that is more than 60 blocks of air between the still intact sapling and the "tree".

Natura: 4.1.0.56
Minecraft: 1.10.2

**Comment by alexbegt** [comment]
Does it look like this http://i.imgur.com/WDF7tDI.png or is there a lot of open space around the saplings?

**Comment by nohelix** [comment]
There is a lot of open space. http://imgur.com/FodzRQA (shown here in the nether but was the same in the overworld).

Here (http://imgur.com/CHCkhOT) is the single layered trunk.

**Comment by alexbegt** [comment]
I have figured it out! If you put a second layer of nether rack above your first layer, the tree will grow in the way that it should. Like this: http://i.imgur.com/QHWrIvT.png

**Comment by alexbegt** [comment]
It seems I forgot something from 1.7.10 when I created the world generator for bloodwood haha.

**Comment by alexbegt** [comment]
Once natura-1.10.2-4.1.0.65/natura-1.11.2-4.2.0.20 goes up on curseforge, it will have the fix for this issue, but for now you will need to put two layers of Netherrack down for the bloodwood tree not to grow at y level 0!
