### ISSUE TITLE
Add bookshelves to ore dictionary

### ISSUE THREAD

**Issue by mainrs** [progwml6/Natura#364]
Would you mind adding the bookshelves to the ore dictionary? The vanilla one has the entry `ore:bookshelf`.  The same entry is used by BOP with their bookshelves.

**Comment by mainrs** [comment]
@progwml6 Are you fine if I create a PR? Would then add all woods to the dictionary.

**Comment by progwml6** [comment]
Adding all the bookshelves to the forge set value is fine w/ me.

**Comment by alexbegt** [comment]
Has been implemented!
