### ISSUE TITLE
Crafting Tables non-functional in 1.11.2

### ISSUE THREAD

**Issue by Lupinarius** [progwml6/Natura#366]
I can craft the crafting tables from natura woods, for example ghostwood, but once placed the crafting table does not function at all. I am running Minecraft 1.11.2 and the 13.20.0.2310 build of Forge.

**Comment by alexbegt** [comment]
What version of Natura are you running?

**Comment by alexbegt** [comment]
If you aren't already, I recommend running natura-1.11.2-4.2.0.20 as that has a bug fix for not being able to open crafting tables.

**Comment by Lupinarius** [comment]
Sorry about the long delay in getting back to you. The link I downloaded from did not make the version clear, and as it turns out it was 1.11.2-4.2.0.16 I had downloaded. updated and the issue is now fixed. Thank you for your help. Closing Issue.
