### ISSUE TITLE
Tainted soil carpets the sea floor, but is not oregenreplaceable

### ISSUE THREAD

**Issue by purpleposeidon** [progwml6/Natura#368]
This is typical:
![image](https://user-images.githubusercontent.com/150333/26962368-90b89b28-4c9a-11e7-9198-5db5c9343b8a.png)
It looks to me that the tiny little patches of netherrack only happen beneath gravel/soulsand/clouds.

It makes [Railcraft Firestone oregen](https://github.com/Railcraft/Railcraft/issues/1247) pretty much impossible.

**Comment by CovertJaguar** [comment]
In your block, add:

```
@Override
public boolean isReplaceableOreGen(IBlockState state, IBlockAccess world, BlockPos pos, com.google.common.base.Predicate<IBlockState> target){
   return target.apply(state) || target.apply(Blocks.NETHERACK.getDefaultState());
}
```

**Comment by alexbegt** [comment]
Is this 1.10.2 or 1.11?

**Comment by CovertJaguar** [comment]
1.10.2 is were we are using it.
