### ISSUE TITLE
Overworld Saplings not growing

### ISSUE THREAD

**Issue by Dilnu** [progwml6/Natura#369]
Hi, overworld saplings from the first overworld sapling item (Maple etc) aren't growing in my world.

I just tried growing a maple sapling with default configs at Y = 82 on the 1.10 version.

Specifically Minecraft 1.10.2, Forge 12.18.3.2297, Mantle 1.1.5, Natura 4.1.0.65

I also have JEI version 3.14.7.420 but that seems unlikely to be related.

My config is here: https://pastebin.com/3iMGUwCZ I haven't changed anything from defaults though.

**Comment by Landmaster** [comment]
@Dilnu I've seen a similar problem in programming the mod [LandCraft](https://github.com/Landmaster/LandCraft) before: I think [this function](https://github.com/progwml6/Natura/blob/1.10/src/main/java/com/progwml6/natura/world/worldgen/trees/overworld/OverworldTreeGenerator.java#L87) is reponsible.
