### ISSUE TITLE
[1.10.2-4.1.0.65] No right-click on Cotton like in 1.7.10.

### ISSUE THREAD

**Issue by eyeonus** [progwml6/Natura#371]
I don't know if it's not implemented yet, or some kind of weird mod interaction with one of the other mods in the Direwolf20 pack, but I remember on 1.7.10 right-clicking these two would harvest, and it's not happening in my 1.10.2 world.

**Comment by KnightMiner** [comment]
I don't think it existed natively in 1.7, I recall having to add the feature using the EnderCore config

**Comment by eyeonus** [comment]
Possibly that's true for barley, but I know it did that for cotton. I even double-checked the FTB wiki, which says right-clicking cotton plants yields cotton but no seeds, and reverts the cotton plant back to the pink bud growth level.

**Comment by KnightMiner** [comment]
Hmm, I don't remember cotton specifically. I thought I added the feature, but then again I had at least three types of cotton in my 1.7 pack

**Comment by progwml6** [comment]
other mods added the right click harvesting capabilities in the past, Natura has never done it natively

**Comment by eyeonus** [comment]
I just tested it in 1.7.10 and you are correct, there is no right-click harvest for barley.

But the right-click harvest for cotton is a thing in 1.7.10, no other mods (except mantle):
https://youtu.be/iHGP3B0lKw0

**Comment by sandalle** [comment]
https://minecraft.curseforge.com/projects/simpleharvest can be used to add right-click harvesting to modded plants, but requires JSON configs and possibly a custom IReplantHandler (see https://github.com/TehNut/Harvest/blob/1.9/src/main/java/tehnut/harvest/IReplantHandler.java ). I haven't gotten it to work with Natura plants yet. Natura might be able to implement some hook for this to auto-generate the JSON entries and implement, if necessary, an IReplantHandler.
