### ISSUE TITLE
Bone Meal Bag conflicting recipe

### ISSUE THREAD

**Issue by Jeffman12** [progwml6/Natura#373]
Bone meal bags now conflict with the new Bone Blocks at the workbench/crafting station.

**Comment by KnightMiner** [comment]
Bone blocks also double as storage, so the bone meal bag might be redundant now

**Comment by progwml6** [comment]
we can have the recipe use blocks as the Natura item allows for 3x3 bone meal applications

**Comment by alexbegt** [comment]
There are no longer any recipe conflicts!
