### ISSUE TITLE
[1.11.2] Entity names aren't properly localized

### ISSUE THREAD

**Issue by Lykrast** [progwml6/Natura#375]
The various mobs have their name display as unlocalized on the spawn eggs.
![heatscar_name](https://user-images.githubusercontent.com/8684850/27807140-2c504dbc-603f-11e7-86a0-6437b2adb762.png)

Natura version is 1.11.2-4.2.0.22

**Comment by alexbegt** [comment]
Thanks for the bug report! As a side note, I recommend leaving heatscar spiders disabled as their speed is currently bugged.

**Comment by alexbegt** [comment]
Has been fixed in 1.12!
