### ISSUE TITLE
crash with Natura 4.2.0.24

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#376]
A crash occurs during Minecraft loading at the first step with Natura 4.2.0.24 https://pastebin.com/GjQ2aL7R. I use Forge 13.20.1.2393.

**Comment by alexbegt** [comment]
Please downgrade back to 4.2.0.22, the current builds are bugged.

**Comment by alexbegt** [comment]
Alright the uploaded build, 4.2.0.24 has been fixed and re-uploaded to curse.

**Comment by alexbegt** [comment]
Did 4.2.0.24 work for you?

**Comment by 0Navis0** [comment]
Sorry for the late answer, yes nw it works. ^w^
