### ISSUE TITLE
[1.12][Request] Nether Configs

### ISSUE THREAD

**Issue by NielsPilgaard** [progwml6/Natura#379]
Hi! 
I would really like a config option to turn Heat Sand and Tainted Soil on/off, if possible.

**Comment by alexbegt** [comment]
Heat Sand and Tainted Soil only spawn if overrideNether is set to true.

**Comment by NielsPilgaard** [comment]
I realize that, but I'd like to keep some of the other nether decorations, especially the trees.

**Comment by alexbegt** [comment]
The trees will still spawn, Just there will not be any Heat Sand or Tainted Soil spawning

**Comment by NielsPilgaard** [comment]
Oh I see, thanks for clearing that up :)

**Comment by NielsPilgaard** [comment]
Having overrideNether set to false does seem to remove the nether trees, fyi.

**Comment by alexbegt** [comment]
Can you upload your natura.cfg and NaturaModules.cfg for me? As trees still spawn on my end when overrideNether is disabled in natura.cfg

**Comment by NielsPilgaard** [comment]
I was just re-reading the NaturaModules.cfg, and realized the description has changed to "# All of the nether blocks including trees", so it is working as described, sorry about that.

**Comment by alexbegt** [comment]
Okay, the new version of natura that will be published soon has the option to just disable heat sand and tainted soil.

**Comment by NielsPilgaard** [comment]
Thank you, I really appreciate it!

**Comment by alexbegt** [comment]
I am going to go ahead and close this issue, I hope the new config settings work for you!

**Comment by NielsPilgaard** [comment]
Oh right, completely forgot to close this. The configs work perfectly, thanks!
