### ISSUE TITLE
[1.12] Wither Skeletons not spawning with sponge

### ISSUE THREAD

**Issue by tgstyle** [progwml6/Natura#385]
Not sure what is going on here but I have narrowed it down to Natura and sponge together. Wither skeletons will not spawn when both are installed. Seems to be they may get replaced by zombie pigman?

**Comment by tgstyle** [comment]
Removal of sponge makes everything spawn properly again, also seems blaze get replaced by zombie pigman.

**Comment by tgstyle** [comment]
Blaze spawners still work with sponge+natura.

**Comment by Yorkforce** [comment]
Just to add more confusion, were having the same problem on Horizons 3 server, which doesn't have natura installed.
