### ISSUE TITLE
TinkersConstruct Crafting Stations do not appear on JEI 

### ISSUE THREAD

**Issue by trilexcom** [progwml6/Natura#386]
this issue log was posted at TC issue, 

Imnuts7 posted this 

Those such as Stencil Table, Crafting Station etc. do not appear on JEI with the mods I have installed but everything else in the mod is shown. They are still shown if referred to in recipes and I saw with only JEI and TC installed they are shown, therefore I conclude there is some conflict between some of the mods.

when we have natura and Tinkers Contruct installed together in 1.12 all the aboe happens

if you remove Natura everything comes back. you can see the Stencil table and everything in JEI.

Forge Version : 2426
TC : TConstruct-1.12-2.7.2.15
Natura Version : 1.12-4.3.0.10

Thanks 

Mat (TrilexCom)

**Comment by Imnuts7** [comment]
Strange...On my computer they are still shown with Natura installed.

**Comment by KnightMiner** [comment]
This is not a Natura issue, or a JEI or Tinkers issue really. JEI automatically hides any items that have too many variants, and by adding Natura you increased the amount of variants of the table. To fix, increase the allowed variants in the JEI config or disable showing all variants in the Tinkers Construct config.
