### ISSUE TITLE
[1.11.2] Suggestion: Allow glowshroom blocks to be mined with silk touch

### ISSUE THREAD

**Issue by LachimHeigrim** [progwml6/Natura#391]
It seems the glowshroom blocks currently cannot be harvested: they always drop corresponding glowshroom item, regardless of tool. Besides looking amazing (mood lighting ... :) ), I'm tempted to use them in some custom recipes, I'm sure something could be squeezed out of them (pun intented).

Also it would be more consistent with vanilla mushroom blocks which can be harvested using silk touch (tested axe).

**Comment by alexbegt** [comment]
Support for using silk touch on mushroom blocks has been added!

**Comment by LachimHeigrim** [comment]
Thanks sir!
