### ISSUE TITLE
[1.12-4.3.0.16] Barley Seeds Placed Automatically Turn Into Cotton Seeds

### ISSUE THREAD

**Issue by BrendanTA** [progwml6/Natura#394]
This happens with the following:
MC 1.12
Forge: forge-14.21.1.2443
Actually Additions 1.12.1-r119
Natura 1.12-4.3.0.16

[![Screenshot from Gyazo](https://gyazo.com/43ac7daddfe7119fffe79d2ac7078783/raw)](https://gyazo.com/43ac7daddfe7119fffe79d2ac7078783)

As seen above I place barley seeds in a placer from actually additions, and this is what comes out...
[![Screenshot from Gyazo](https://gyazo.com/055effc2049abcfab13b83b1f25525e8/raw)](https://gyazo.com/055effc2049abcfab13b83b1f25525e8)

Cotton seeds, this happens with Industrial foregoing, and any other machine seed placing block. It just won't plant barley.

**Comment by alexbegt** [comment]
Does this still occur? It seems that the developer of Industrial-Foregoing might've fixed it on Sep 2nd. If it does still occur, please open a new ticket!

**Comment by iNilo** [comment]
ActuallyAdditions places cotton too ( https://github.com/Ellpeck/ActuallyAdditions/issues/1207 )  with its  Farmer https://ftb.gamepedia.com/Farmer_(Actually_Additions)

on FTB Revelation 3.4.0 (Natura 1.12.2-4.3.2.69 and Actually Addons 1.12.12-r150)
