### ISSUE TITLE
tained soil and heat sand don't spawn with NetherEx

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#397]
Now Natura doesn't prevent more the BiomesOPlenty and NetherEx biomes to spawn in the nether when the nether override option is true, but the tained soil and heat sand still don't spawn.

**Comment by alexbegt** [comment]
"Generate Tainted Soil" and "Generate Heat Sand" are both set to true in the config file? (I just noticed it's "tained" and not "tainted".

**Comment by 0Navis0** [comment]
Yes they are set on true.

**Comment by alexbegt** [comment]
What version of Minecraft?

**Comment by 0Navis0** [comment]
Both 1.11.2 and 1.12.1 have the issue.

**Comment by 0Navis0** [comment]
Any progress with this issue ?

**Comment by alexbegt** [comment]
The latest versions of Natura for 1.12.2 should allow the tainted soil + heat sand to spawn in the nether by replacing NETHERRACK and SOUL_SAND + if the biome has a type of "Nether", Can you try with the latest one?

**Comment by Hypsellis** [comment]
I just tried and it doesn't work with BiomesOPlenty and NetherEx.

**Comment by 0Navis0** [comment]
It works with only BOP but it spawn in small amounts. The problem comes with NetherEx.

**Comment by Kyrinon** [comment]
NetherEx completely over rites the nether with its own generator. If you want the Natura blocks you will have to add them to NetherEx cfg. You can add them as an ore or I just replaced the "topBlock" with "natura:nether_heat_sand" under the "torrid_wasteland" and "natura:nether_tainted_soil" under "hell"
