### ISSUE TITLE
Right-click harvesting of crops not working in 1.12.1

### ISSUE THREAD

**Issue by isochronous** [progwml6/Natura#400]
Playing All the Mods 3, using natura 4.3.0.17 and forge 14.22.0.2467, it's no longer possible to harvest barley or cotton by right-clicking - you have to break and replace it. I know this was fixed in older versions, but it seems to be broken again.

**Comment by winsrp** [comment]
same here missing my right click...

**Comment by alexbegt** [comment]
This has been added to the newer versions of Natura, It seems I added it Oct 21st but never closed this ticket! If it still does not work with the latest versions, please reopen a new ticket!
