### ISSUE TITLE
Overworld clouds spawn in a single line.

### ISSUE THREAD

**Issue by DefinitelyNotFred** [progwml6/Natura#403]
Clouds follow the simple formula of z=x, passing through the origin at x=0, z=0. I've traveled and teleported quite far to see if they spawn anywhere else in the world and can say with reasonable confidence that they don't. I'm using Mantle 1.10.2-1.1.5, Natura 1.10.2-4.1.0.80, and Forge 12.18.3.2185 with no other mods installed. Same thing happened in Natura 1.10.2-4.1.0.73 as well.
Picture: ![2017-09-15_00 57 41](https://user-images.githubusercontent.com/30205205/30468465-20507d60-99b1-11e7-9955-3aa89844d94c.png)

**Comment by DefinitelyNotFred** [comment]
Also see https://github.com/progwml6/Natura/issues/398

**Comment by 0Navis0** [comment]
Is there any progress about it ?

**Comment by Shahelion** [comment]
Also applies to the clouds in the End.

![2017-12-02_23 05 31](https://user-images.githubusercontent.com/6917535/33523193-9841096a-d7b5-11e7-8f7a-27910b1a34f1.png)

**Comment by alexbegt** [comment]
https://i.imgur.com/bh17SEg.png Clouds have been fixed!
