### ISSUE TITLE
[1.12-4.3.0.23] Door textures are flipped incorrectly and recipe is inconsistent with Vanilla

### ISSUE THREAD

**Issue by dewiniaid** [progwml6/Natura#411]
Using Natura 1.12-4.3.0.23 (latest available according to Twitch) and Forge 14.18.3.2511, as part of a (heavily modified) FTB Beyond III install:

Sakura doors (and possibly other Natura doors as well, not tested) do not properly flip their texture based on door orientation -- the texture will either be oriented wrong when the door is closed, or oriented wrong when the door is open.  Example: https://i.imgur.com/CmxpaF1.png

The door closest to the camera in this screenshot has the hinges on the left side when it is closed, but they should be on the right.  It is rendered correctly when open.  Additionally (not visible in the screenshot), the darker pixels representing the hinges are rendered on the swinging edge of the door when it is open in addition to being on the corrected hinged edge.  (This might be a texturing issue, the edges are the same 3 pixel wide texture as the first 3 pixels of the hinged side)

The door further from the camera has the same issue but in reverse: it's textured correctly when closed, but is backwards when open.  It opens the opposite direction -- i.e. both doors will be to the camera's right when open.

Additionally, the recipe for vanilla doors creates 3 doors.  The recipe for Natura doors only creates 1.

**Comment by dewiniaid** [comment]
Confirmed this also happens with Eucalyptus doors.  Also, noticed there is no Silverbell door.

**Comment by KShellz** [comment]
Any resolution to this problem? I am also having the same issue with the doors having their textures flipped. This only happens when I am placing double doors, The hinges on the right door are always on the left instead of the right, except when I open the door the hinges flip to the proper side.
