### ISSUE TITLE
[1.12.2] Cascading Worldgen

### ISSUE THREAD

**Issue by Shahelion** [progwml6/Natura#419]
[16:48:22] [Server thread/WARN] [FML]: Natura loaded a new chunk (118, 118  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Also, of all the mods that have this message pop up (and there seem to be quite a few) this one is by far the worst. Most of the others only have it appear once, maybe twice. This one has appeared roughly three to six times for every one other mod that does it.

**Comment by progwml6** [comment]
can you post the full log please

**Comment by Shahelion** [comment]
The rest of the logs are unrelated, this message just pops up several times in a row every so often when exploring with absolutely nothing else in the console. It's the same every time except for the time and location.

It probably appears more than others simply because Natura has a lot more worldgen, is my guess.

**Comment by progwml6** [comment]
I need to understand how the logic is broken which necessitates having access to a full log

**Comment by labpaw** [comment]
@progwml6 https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/ here you go.

**Comment by alexbegt** [comment]
@Zsashas If you don't want to provide the full log, please provide the natura modules that you have enabled, as the log would tell me this.

**Comment by alexbegt** [comment]
Also, do you happen to have cloud generation enabled?

**Comment by Shahelion** [comment]
I do have the clouds, yes. Even though it's just a giant diagonal line, it helps with navigation and looks kind of cool still.

**Comment by alexbegt** [comment]
https://i.imgur.com/bh17SEg.png Clouds have been fixed!

**Comment by Skijearz** [comment]
Natura is still causing cascading worldgen lag for me :
`  "Natura loaded a new chunk [220, 173] in dimension 0 (overworld) while populating chunk [221, 174], causing cascading worldgen lag." `
I do have all of the modules in the NaturaModules.cfg set to true

**Comment by alexbegt** [comment]
@Zsashas What version of the mod are you running?

**Comment by Skijearz** [comment]
Natura : 1.12.2 - 4.3.2.66
