### ISSUE TITLE
I don't think your trees are supposed to render like that...

### ISSUE THREAD

**Issue by Sunconure11** [progwml6/Natura#425]
![screenshot 2018-01-10 17 47 12](https://user-images.githubusercontent.com/5614902/34799577-56defa4e-f62e-11e7-9785-38fcf5c00f19.png)

**Comment by alexbegt** [comment]
What version are you running, and what other mods?

**Comment by Sunconure11** [comment]
natura-1.12.2-4.3.2.39
Forge 14.23.1.2587
I am running a bunch of other mods, but the only one that could be remotely touching appearances is Dynamic Surroundings.
