### ISSUE TITLE
See-through leaves

### ISSUE THREAD

**Issue by Raelzaryn** [progwml6/Natura#427]
## Version Information
`Minecraft: `1.12.2
`Forge: `14.23.1.2587
`Mantle: `1.2.1.21
`Natura: `4.3.2.39

## Report Information
Leaves only render the outmost texture (making them pretty much completely seethrough regardless of how many leaves are behind it.

## Steps to Reproduce
Immediatly appears. Downgrading to natura 4.3.1.35 removes this.

**Comment by alexbegt** [comment]
Once natura-1.12.2-4.3.2.42 goes live on curseforge this bug should be fixed. If it isn't, please reopen a new ticket!
