### ISSUE TITLE
Missing Maven builds

### ISSUE THREAD

**Issue by elifoster** [progwml6/Natura#434]
## Version Information
`Minecraft: ` 1.12
`Forge: ` N/A
`Mantle: ` N/A
`Natura: ` N/A

## Report Information

It [appears](http://dvs1.progwml6.com/files/maven/com/progwml6/natura/Natura-1.12/maven-metadata.xml) that the Maven repo is missing the past 35 or so builds. The only build that's on the Maven doesn't work with newer MCP mappings, but this has since been fixed in newer builds.

## Steps to Reproduce

N/A

## Crash Log

N/A

## Forge Log

N/A

**Comment by progwml6** [comment]
http://dvs1.progwml6.com/files/maven/com/progwml6/natura/natura/maven-metadata.xml is the correct maven metadata file. the Natura-1.12 only shows up when @alexbegt commits the files he uses do differentiate different versions in his IDE
