### ISSUE TITLE
slime tree

### ISSUE THREAD

**Issue by B013040034** [progwml6/Natura#435]
It's strange to slime tree!!!
the orange one can get the orange trunk
but other color slime tree is original ones 
can you fix the problem?

--by Taiwanese player

**Comment by SweetSugarSugar** [comment]
Slime Saplings and such aren't even from Natura...

**Comment by alexbegt** [comment]
As @SweetSugarSugar stated, Natura does not add Slime Saplings, instead those are from Tinkers Construct. Please report this to them.
