### ISSUE TITLE
Sulfur clouds not being generated

### ISSUE THREAD

**Issue by Tyler799** [progwml6/Natura#436]
Sulfur clouds are not generated in the nether with the default config settings. 

## Version Information
`Minecraft: ` 1.12.2
`Forge: ` Build 2624
`Mantle: ` 1.3.1.21
`Natura: ` 4.3.2.42

## Report Information
Sulfur clouds are not generated in the nether with the default config settings. 

## Steps to Reproduce
Go to the nether. No sulfur clouds. :(

**Comment by SweetSugarSugar** [comment]
And... have you tried changing those config settings?

**Comment by Tyler799** [comment]
The config settings have sulfur clouds enabled by default. I don't see how changing them would fix anything.

    B:"Generate Sulfur Clouds"=true
    I:"Sulfur Cloud Spawn Height"=40
    I:"Sulfur Cloud Spawn Range"=78
    I:"Sulfur Cloud Spawn Rarity"=8
     I:"dimension blacklist(sulfur clouds)" <
     >

**Comment by alexbegt** [comment]
Is `B:"Enable Clouds"=true`?

**Comment by Tyler799** [comment]
Nope. Thanks. Apparently that's disabled by default...for some reason. Faaaak.
