### ISSUE TITLE
Config to disable mobs

### ISSUE THREAD

**Issue by GraniteDevil** [progwml6/Natura#447]
There is no config option to disable specific mobs.  When downloading this mod, I expected worldgen only (as that is what is in the description) and I do not need exploding nether creepers or other mobs but I still need regular, vanilla, hostile mobs.

**Comment by alexbegt** [comment]
If you disable the Entities pulsar inside of NaturaModules.cfg, any entity added by natura will be removed. Which includes the nether creepers and imps.
