### ISSUE TITLE
Recipe Problems

### ISSUE THREAD

**Issue by Serifina** [progwml6/Natura#449]
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` Any
`Mantle: ` Any
`Natura: ` Any

Natura recipes for wood items are out of date. The Natura-specific sticks don't always craft (it seems to be random from modpack to modpack if you'll create Minecraft's sticks or Natura's sticks) leaving all the Natura-specific wood items impossible to craft much of the time.

Fences and fence gates are easily fixed by moving to the new style of recipe for them that Minecraft uses now (using wood blocks and sticks for fences and gates both) and the recipes should be updated to match. The other wood-specific items seem unnecessary (Minecraft doesn't have wood type specific tools) but if they need to be kept, then something needs to be done to make them reliable to craft.

**Comment by wolfdarkstar** [comment]
yes I have same problem cant use silverbellwood to make sticks makes only standard MC sticks  so I cant make SBW fence or gate :-( 
or would a crafting tweak / mod fix this ? 

can someone pleas look in to this Thank you for your time ..
