### ISSUE TITLE
[feature request] dynamic trees compat for natura

### ISSUE THREAD

**Issue by malice936** [progwml6/Natura#450]
Compatibility for the Natura trees to have dynamic versions, and generate them when [Dynamic Trees](https://minecraft.curseforge.com/projects/dynamictrees) is installed

**Comment by Zarepheth** [comment]
This is a duplicate of [Issue 441](https://github.com/progwml6/Natura/issues/441)

**Comment by alexbegt** [comment]
As posted by @Zarepheth This is a duplicate of #441
