### ISSUE TITLE
Memory leak because of Berry Medley

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [progwml6/Natura#459]
if you make 2, stack them in your inventory and keep playing
sooner or later it will cause erratic behaviour
explained by a memory leak on server
about which it will repeatedly complain

it has something to do with player having a stack of items which DON'T stack
as a result, the more you interact with your inventory
the more bugs accumulate on server
because one of your inventory slots by all rights SHOULD be occupied,
by keeping playing on server, it causes memory leak, as I said
and server gets stuck

it still works, i. e. you can play
but the console deadlocks
you cannot input any commands
and, here's the important thing
you can't shut it down properly
with 'stop' command
reloading server causes weird stuff to happen
this is when save gets corrupted
I literally had my backpack as a helmet for instance
and blocks got replaced
I got nuclear fuel in the middle of the field
village home suddenly became made of lime wood fence gates

and the only time I didn't get my world corrupted
was when I separated the berry thingies into different inventory slots

## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 2738
`Mantle: ` 1.3.2.24
`Natura: ` 4.3.2.49

**Comment by alexbegt** [comment]
Do you have a log from the server?

**Comment by Pythonic-Rainbow** [comment]
@alexbegt sorry I deleted it

**Comment by alexbegt** [comment]
I am unable to recreate this issue, plus I had to make it so Berry Medley wouldn't stack so I am a bit confused on hows yours is stacking.

**Comment by Pythonic-Rainbow** [comment]
Being unable to replicate the issue, we are now closing this.
