### ISSUE TITLE
Hopseed Trees will not spawn

### ISSUE THREAD

**Issue by MountainWulf** [progwml6/Natura#468]
Minecraft: 1.12.2
Forge: 14.23.4.2705
Mantle: 1.12-1.3.2.24
Natura: 1.12.2-4.3.2.62

I've been playing in a new save for a few weeks now and have spent hours trying to find a hopseed tree, but to no avail. I spent so many hours trying to find one that I started to suspect they weren't spawning.

I started a new world that was a copy of my regular world and went around in spectator mode and saw none, so I made another one that only had Mantle and Natura, went around in several different worlds in spectator mode, but still could find none. I used the config to set the spawn rate really high in case they were just too rare, but still no spawns.

All the other trees spawn just fine, except there is also no redwood, but that isn't odd to me, I've been playing Natura since it came out and I've never seen a redwood before, or imps come to think of it, but again, those never spawn, so that's normal too. Run on sentence much?

I spawned saplings in and used hundreds of bonemeal, but they wouldn't grow. Again, I had only Natura and Mantle installed by this point in my testing. Let me know if I'm doing something wrong or can fix it easily. Keep in mind I have 0 coding ability though. 

Forge Log

I don't really know how to find the forge logs, so hopefully they aren't needed.

**Comment by MountainWulf** [comment]
I went and did more testing on the other saplings in creative. They all work fine except for the redwood. If any sapling but the center sapling try to grow, it wipes out all the saplings without growing anything at all. So the tree will only grow if you can get all the saplings down and bonemeal the center one quickly enough. Might be why I've never seen one of those either.

Also, bloodwood trees will only grow at low-ish Y heights. But that might be known about or intended behavior. They won't grow at 120 or above, is that normal?

**Comment by SokyranTheDragon** [comment]
I did some digging and I think I found the issue with hopseed trees. I checked the code for generation, and it seems that it checks if the ground is NOT dirt or grass (HopseedTreeGenerator.java, line 190). I think the negation should be removed in there.

I've also learned that saplings can be placed on farmland, so I checked what would happen if I placed hopseed sapling there. As it turns out, it grew without any issues whatsoever, which makes me believe that the code I've mentioned is the issue.

**Comment by MountainWulf** [comment]
I don't know how to edit that unfortunately. But thank you for finding that out. I'm sure it'll be useful for others.

**Comment by alexbegt** [comment]
There has been a new version of Natura pushed to curseforge to fix this bug: https://minecraft.curseforge.com/projects/natura/files/2711439

**Comment by MountainWulf** [comment]
Nifty. Thank you very much.
