### ISSUE TITLE
Strange behavior when redwood saplings are given bone meal

### ISSUE THREAD

**Issue by TheDeviantCrafter** [progwml6/Natura#476]
## Version Information
`Minecraft: ` 1.12.2 
`Forge: ` 14.23.5.2807
`Mantle: ` 1.3.3.39
`Natura: ` 4.3.2.66

## Report Information

Redwood saplings respond strangely when bone meal is applied. If you create a grid of 7 x 7 redwood saplings and apply bone meal to the middle sapling, it instantly grows into a full redwood tree.

If you bone meal a redwood sapling that isn't in the middle, such as a corner, it doesn't grow. Instead it deletes all other redwood saplings in a 7 x 7 area, leaving only the sapling you applied bone meal to.

I don't think redwood trees are intended to respond to bone meal at all.

## Steps to Reproduce
1. Create a 7 x 7 field of redwood saplings
2. Apply bone meal to the center sapling
3. Repeat step 1
4. Apply bone meal to a corner sapling

## Forge Log
https://gist.github.com/TheDeviantCrafter/f21f8d7a4aba99c0f57a99a273191d38

**Comment by ghost** [comment]
Can confirm this with forge 2800, same natura version
