### ISSUE TITLE
[Extend the BlockLog of trees´ logs] [Sugestion]

### ISSUE THREAD

**Issue by Pokesmile-modded** [progwml6/Natura#486]
I have a problem with the modpack that I am creating, I have a mod called Advent Of Ascension in which there is skills. You can level up these skills breaking blocks like Stone (Foraging) or wooden logs (Logging) Natura trees don´t give logging experience. I asked the mod creator if this was an issue but he told me that ¨Tell those mods to make their logs extend BlockLog... like they should.¨

Sorry If wrote something wrong my english is not as good as i would want it to be :)

**Comment by progwml6** [comment]
Unfortunately, implementing this change in 1.12.2 is not going to be possible. We are going to evaluate it for 1.14.4. In the meantime .... does Advent of Ascension have an API that we can integrate with to provide this experience?

**Comment by Pokesmile-modded** [comment]
I don´t think Advent Of Ascension has any API, althought it doesn´t have any mod compatibility support (appart from PlusTiC) I think I should ask the creator of the mod to make a file in the config for adding white-listed skill-breaking blocks. Thanks!

**Comment by progwml6** [comment]
I'm happy to try to work with the Dev to fix this if we can in some other way for 1.12.2. If you need something further, or API integration becomes an option, feel free to re-open this issue.
