### ISSUE TITLE
Question regarding default config values

### ISSUE THREAD

**Issue by xJon** [progwml6/Natura#492]
Using the 1.12.2 version of the mod, both clouds and redwood trees are disabled by default:
```
    B:"Enable Clouds"=false
...
    B:"Generate Redwood Trees"=false
```
Is there any specific reason for that?
Thanks!

**Comment by progwml6** [comment]
A large number of the users disliked the clouds so we disabled them by default. The redwoods can cause lag, as well as unintentionally breaking things nearby when planting due to the large size, so for safety they were disabled by default

**Comment by xJon** [comment]
Thanks for the quick reply.
